package com.wanderwildwood.kinokocho.ui

import com.wanderwildwood.kinokocho.R

/**
 * The drawing for a character state, and the mushroom it was drawn from.
 *
 * Generated by tools/make-art.py. Do not edit by hand.
 *
 * Naming the species is not the app identifying anything — it is saying what the
 * picture is of, the way a field guide captions a plate. A reader who wants to know
 * why decurrent looks like that gets an answer; the mushroom in their hand is never
 * named by this app.
 */
data class Art(val drawable: Int, val species: String?, val note: String)

object CharacterArt {

    private val byState: Map<String, Art> = mapOf(
        "cap_colour_pattern/darker_centre" to Art(R.drawable.art_cap_colour_pattern_darker_centre, "Amanita parcivolvata", "A darker disc at the centre fading outwards."),
        "cap_colour_pattern/paler_margin" to Art(R.drawable.art_cap_colour_pattern_paler_margin, "Panaeolus papilionaceus", "Dark over most of the cap, with a pale band at the edge."),
        "cap_colour_pattern/uniform" to Art(R.drawable.art_cap_colour_pattern_uniform, "Russula virescens", "One tone across the whole cap, seen from above."),
        "cap_margin/appendiculate" to Art(R.drawable.art_cap_margin_appendiculate, "Coprinus comatus", "Fragments of the veil left hanging from the edge."),
        "cap_margin/incurved" to Art(R.drawable.art_cap_margin_incurved, "Agaricus campestris", "Curved inwards but not rolled."),
        "cap_margin/inrolled" to Art(R.drawable.art_cap_margin_inrolled, "Paxillus involutus", "Rolled right under, so the edge points back at the stem."),
        "cap_margin/straight" to Art(R.drawable.art_cap_margin_straight, "Russula virescens", "Meeting the cap surface at a straight edge."),
        "cap_margin/striate" to Art(R.drawable.art_cap_margin_striate, "Amanita parcivolvata", "Grooved at the edge, following the gills beneath."),
        "cap_margin/translucent_striate" to Art(R.drawable.art_cap_margin_translucent_striate, "Mycena galericulata", "Flesh thin enough that the gills show through as lines."),
        "cap_margin/uplifted" to Art(R.drawable.art_cap_margin_uplifted, "Clitocybe gibba", "Turned up with age, exposing the gills from the side."),
        "cap_margin/wavy" to Art(R.drawable.art_cap_margin_wavy, "Cantharellus lateritius", "Irregularly lobed and waved rather than circular."),
        "cap_shape/bell" to Art(R.drawable.art_cap_shape_bell, "Panaeolus papilionaceus", "Sides curve out and hang down: a bell, not a cone."),
        "cap_shape/conical" to Art(R.drawable.art_cap_shape_conical, "Hygrocybe conica", "Straight sides meeting at a point; never flattening with age."),
        "cap_shape/convex" to Art(R.drawable.art_cap_shape_convex, "Agaricus campestris", "An even dome, the margin still turned down."),
        "cap_shape/depressed" to Art(R.drawable.art_cap_shape_depressed, "Lactarius deliciosus", "Flat, but sunk in the middle — not yet a funnel."),
        "cap_shape/egg" to Art(R.drawable.art_cap_shape_egg, "Coprinus comatus", "Taller than wide, sides near-parallel, before any expansion."),
        "cap_shape/flat" to Art(R.drawable.art_cap_shape_flat, "Russula virescens", "Expanded flat, the margin level with the centre."),
        "cap_shape/funnel" to Art(R.drawable.art_cap_shape_funnel, "Clitocybe gibba", "The whole cap slopes into the stem; the hollow reaches the flesh."),
        "cap_shape/umbilicate" to Art(R.drawable.art_cap_shape_umbilicate, "Arrhenia epichysium", "A small sharp navel at the centre of an otherwise flat cap."),
        "cap_shape/umbonate" to Art(R.drawable.art_cap_shape_umbonate, "Amanita parcivolvata", "A broad cap with a distinct raised boss at the centre."),
        "fruitbody_type/bolete" to Art(R.drawable.art_fruitbody_type_bolete, "Boletus edulis", "Underneath: round tube mouths in a thick soft layer; the stem is stout."),
        "fruitbody_type/chanterelle_like" to Art(R.drawable.art_fruitbody_type_chanterelle_like, "Cantharellus lateritius", "Underneath: blunt forking ridges, thick and rounded where a gill is thin."),
        "fruitbody_type/coral_club" to Art(R.drawable.art_fruitbody_type_coral_club, "Ramaria stricta", "Repeatedly forking upright branches from a common base, no cap anywhere."),
        "fruitbody_type/cup_disc" to Art(R.drawable.art_fruitbody_type_cup_disc, "Peziza badia", "An ascomycete cup, sessile, hymenium on the inner face."),
        "fruitbody_type/flask" to Art(R.drawable.art_fruitbody_type_flask, "Hypoxylon fragiforme", "A hard cushion on wood, cut to show flask-shaped chambers with necks to the surface."),
        "fruitbody_type/gasteroid" to Art(R.drawable.art_fruitbody_type_gasteroid, "Lycoperdon perlatum", "Spores formed inside; sterile base tapering to the ground, pore at the top."),
        "fruitbody_type/gilled_stemmed" to Art(R.drawable.art_fruitbody_type_gilled_stemmed, "Agaricus campestris", "Underneath: blades radiating from the stem, thin and sharp-edged."),
        "fruitbody_type/jelly" to Art(R.drawable.art_fruitbody_type_jelly, "Tremella mesenterica", "Gelatinous folded lobes with no cap, stem, gills or pores anywhere."),
        "fruitbody_type/other" to Art(R.drawable.art_fruitbody_type_other, null, "Not a taxon: the honest exit when nothing above fits."),
        "fruitbody_type/polypore" to Art(R.drawable.art_fruitbody_type_polypore, "Trametes versicolor", "Underneath: pores far finer than a bolete's, on a tough bracket with no stem."),
        "fruitbody_type/resupinate" to Art(R.drawable.art_fruitbody_type_resupinate, "Stereum ostrea", "A crust lying flat on wood, edge lifting only slightly."),
        "fruitbody_type/toothed" to Art(R.drawable.art_fruitbody_type_toothed, "Hydnum repandum", "Underneath: soft spines hanging down, not blades and not pores."),
        "gill_attachment/adnate" to Art(R.drawable.art_gill_attachment_adnate, "Gymnopus dryophilus", "The gill meets the stem squarely, over its whole depth."),
        "gill_attachment/adnexed" to Art(R.drawable.art_gill_attachment_adnexed, "Mycena galericulata", "The gill touches the stem, but over only the top of its depth."),
        "gill_attachment/decurrent" to Art(R.drawable.art_gill_attachment_decurrent, "Cantharellus lateritius", "The gill does not stop at the stem — it turns and runs down the outside of it."),
        "gill_attachment/free" to Art(R.drawable.art_gill_attachment_free, "Agaricus campestris", "The gill stops short of the stem: a clear gap runs all the way round."),
        "gill_attachment/no_stem" to Art(R.drawable.art_gill_attachment_no_stem, "Pleurotus ostreatus", "Attached to the wood at one side, so there is no stem for a gill to meet."),
        "gill_attachment/notched" to Art(R.drawable.art_gill_attachment_notched, "Tricholoma sejunctum", "The gill runs in deep, then is cut away sharply just before the stem."),
        "gill_edge/different_colour" to Art(R.drawable.art_gill_edge_different_colour, "Mycena galericulata", "The edge is pigmented differently from the gill face."),
        "gill_edge/even" to Art(R.drawable.art_gill_edge_even, "Agaricus campestris", "A clean straight edge, seen face-on."),
        "gill_edge/serrate" to Art(R.drawable.art_gill_edge_serrate, "Lentinellus ursinus", "Regularly toothed, like a saw."),
        "gill_edge/wavy" to Art(R.drawable.art_gill_edge_wavy, "Pleurotus ostreatus", "Undulating without discrete teeth."),
        "gill_extras/forked" to Art(R.drawable.art_gill_extras_forked, "Russula virescens", "Gills dividing in two on their way to the margin."),
        "gill_extras/lamellulae" to Art(R.drawable.art_gill_extras_lamellulae, "Agaricus campestris", "Short gills starting at the margin, not reaching the stem."),
        "gill_extras/veined" to Art(R.drawable.art_gill_extras_veined, "Cantharellus lateritius", "Cross-veins bridging between the ridges."),
        "gill_spacing/close" to Art(R.drawable.art_gill_spacing_close, "Agaricus campestris", "Regularly spaced, distinct, not touching."),
        "gill_spacing/crowded" to Art(R.drawable.art_gill_spacing_crowded, "Marasmius oreades", "So many that the eye cannot separate them at the margin."),
        "gill_spacing/distant" to Art(R.drawable.art_gill_spacing_distant, "Omphalotus illudens", "Few and well apart, with cap flesh visible between."),
        "growth_habit/caespitose" to Art(R.drawable.art_growth_habit_caespitose, "Armillaria mellea", "Clustered, the bases crowded together but still separate."),
        "growth_habit/few" to Art(R.drawable.art_growth_habit_few, "Boletus edulis", "A few, each with its own base, not touching."),
        "growth_habit/fused" to Art(R.drawable.art_growth_habit_fused, "Omphalotus illudens", "Bases run together into one mass — you cannot pull one out alone."),
        "growth_habit/ring" to Art(R.drawable.art_growth_habit_ring, "Marasmius oreades", "A fairy ring: the arc of an outward-growing mycelium."),
        "growth_habit/single" to Art(R.drawable.art_growth_habit_single, "Amanita bisporigera", "One fruitbody, alone."),
        "growth_habit/tiered" to Art(R.drawable.art_growth_habit_tiered, "Trametes versicolor", "Shelving in overlapping tiers up a trunk."),
        "growth_habit/troop" to Art(R.drawable.art_growth_habit_troop, "Marasmius oreades", "Many scattered across the ground, unconnected."),
        "ring/absent" to Art(R.drawable.art_ring_absent, "Russula virescens", "No veil, so no ring is ever left behind."),
        "ring/cannot_tell" to Art(R.drawable.art_ring_cannot_tell, null, "Not a state of the mushroom: the specimen is too old or too damaged to say."),
        "ring/movable" to Art(R.drawable.art_ring_movable, "Amanita jacksonii", "A free collar that slides on the stem rather than gripping it."),
        "ring/skirt" to Art(R.drawable.art_ring_skirt, "Amanita bisporigera", "A membranous veil torn free at the margin and left hanging as a skirt."),
        "ring/zone" to Art(R.drawable.art_ring_zone, "Cortinarius armillatus", "A cortina leaves no membrane, only a fibrous band where it broke."),
        "stipe_base/bulbous" to Art(R.drawable.art_stipe_base_bulbous, "Cortinarius alboviolaceus", "A stem that swells smoothly into a bulb, with no rim where it widens."),
        "stipe_base/buried" to Art(R.drawable.art_stipe_base_buried, null, "Not a mushroom: the base was left in the ground, which is the commonest miss."),
        "stipe_base/equal" to Art(R.drawable.art_stipe_base_equal, "Agaricus campestris", "The same width all the way down, ending flat in the soil."),
        "stipe_base/marginate" to Art(R.drawable.art_stipe_base_marginate, "Amanita citrina", "A bulb with a distinct rim and gutter where the stem meets it."),
        "stipe_base/rhizomorphs" to Art(R.drawable.art_stipe_base_rhizomorphs, "Armillaria mellea", "Cords of mycelium leaving the base and running off through the substrate."),
        "stipe_base/rooting" to Art(R.drawable.art_stipe_base_rooting, "Hymenopellis radicata", "A pseudorhiza: the stem carries on below the soil as a long tapering root."),
        "stipe_base/sac_volva" to Art(R.drawable.art_stipe_base_sac_volva, "Amanita bisporigera", "A membranous bag with a free rim; the stem stands inside it, not fused to it."),
        "stipe_base/tapering" to Art(R.drawable.art_stipe_base_tapering, "Entoloma abortivum", "Narrowing steadily downwards, without ever swelling."),
        "stipe_base/volva_rings" to Art(R.drawable.art_stipe_base_volva_rings, "Amanita muscaria", "No bag — the volva left concentric rings of scales around a bulb."),
        "stipe_flesh/chambered" to Art(R.drawable.art_stipe_flesh_chambered, "Coprinus comatus", "Cross-walls dividing the hollow into chambers."),
        "stipe_flesh/hollow" to Art(R.drawable.art_stipe_flesh_hollow, "Marasmius oreades", "An open tube: the wall is all there is."),
        "stipe_flesh/solid" to Art(R.drawable.art_stipe_flesh_solid, "Boletus edulis", "Filled right through with unbroken flesh."),
        "stipe_flesh/stuffed" to Art(R.drawable.art_stipe_flesh_stuffed, "Agaricus campestris", "A softer pith down the middle, distinct from the wall."),
        "stipe_presence/absent_attached" to Art(R.drawable.art_stipe_presence_absent_attached, "Pleurotus ostreatus", "Joined straight to the wood with no stem at all."),
        "stipe_presence/absent_sitting" to Art(R.drawable.art_stipe_presence_absent_sitting, "Lycoperdon perlatum", "Sitting on the substrate, attached only by cords."),
        "stipe_presence/central" to Art(R.drawable.art_stipe_presence_central, "Agaricus campestris", "The stem meets the cap at its centre."),
        "stipe_presence/lateral" to Art(R.drawable.art_stipe_presence_lateral, "Panellus stipticus", "A short stem at the very edge, against the wood."),
        "stipe_presence/off_centre" to Art(R.drawable.art_stipe_presence_off_centre, "Pluteus petasatus", "The stem meets the cap away from the centre, but not at the edge."),
        "veil_remnants/fibrous_scales" to Art(R.drawable.art_veil_remnants_fibrous_scales, "Pholiota squarrosa", "Recurved scales that are part of the cap skin, not loose patches."),
        "veil_remnants/none" to Art(R.drawable.art_veil_remnants_none, "Russula virescens", "Nothing on the cap: there was no universal veil to leave anything."),
        "veil_remnants/peeling_skin" to Art(R.drawable.art_veil_remnants_peeling_skin, "Pluteus petasatus", "A cuticle lifting and peeling back from the margin."),
        "veil_remnants/single_patch" to Art(R.drawable.art_veil_remnants_single_patch, "Amanita parcivolvata", "One large sheet of veil left sitting on the cap."),
        "veil_remnants/warts" to Art(R.drawable.art_veil_remnants_warts, "Amanita muscaria", "Loose warts of universal veil, easily rubbed or washed off."),
    )

    /** The drawing for a state, or null where none has been drawn yet. */
    fun of(characterId: String, valueId: String): Art? = byState["$characterId/$valueId"]

    /** True when every state of a character has a drawing, so a grid is safe. */
    fun coversAll(characterId: String, valueIds: List<String>): Boolean =
        valueIds.isNotEmpty() && valueIds.all { byState.containsKey("$characterId/$it") }
}
