package com.wanderwildwood.kinokocho.ui

import com.wanderwildwood.kinokocho.R

/**
 * A drawing of the whole mushroom, for the taxa that have one.
 *
 * Generated by tools/install-plates.py. Do not edit by hand.
 *
 * These are not the character drawings. Those are diagrams of one feature — how a gill
 * meets a stem, what a sac volva looks like — and the app draws them itself. A plate is
 * the other thing: a picture of the whole mushroom to hold a real one up against, which
 * is what the candidate page is for and what code cannot honestly produce.
 *
 * Most taxa have none, and that is the ordinary case rather than a gap to apologise for.
 * The page reads perfectly well without one.
 */
object TaxonPlate {

    /** The drawing for a taxon, or null where there is none. */
    fun of(taxonId: String): Int? = PLATES[taxonId]

    private val PLATES: Map<String, Int> = mapOf(
        "agaricus_campestris" to R.drawable.plate_agaricus_campestris,
        "amanita_bisporigera" to R.drawable.plate_amanita_bisporigera,
        "amanita_brunnescens" to R.drawable.plate_amanita_brunnescens,
        "amanita_phalloides" to R.drawable.plate_amanita_phalloides,
        "amanita_rubescens" to R.drawable.plate_amanita_rubescens,
        "galerina_marginata" to R.drawable.plate_galerina_marginata,
        "gyromitra_caroliniana" to R.drawable.plate_gyromitra_caroliniana,
        "hygrophoropsis_aurantiaca" to R.drawable.plate_hygrophoropsis_aurantiaca,
        "inocybe_rimosa" to R.drawable.plate_inocybe_rimosa,
        "lycoperdon_perlatum" to R.drawable.plate_lycoperdon_perlatum,
        "paxillus_involutus" to R.drawable.plate_paxillus_involutus,
        "pleurocybella_porrigens" to R.drawable.plate_pleurocybella_porrigens,
    )
}
