package com.wanderwildwood.kinokocho.ui

import com.wanderwildwood.kinokocho.R

/**
 * A drawing of the whole mushroom, for the taxa that have one.
 *
 * Generated by tools/install-plates.py. Do not edit by hand.
 *
 * These are not the character drawings. Those are diagrams of one feature — how a gill
 * meets a stem, what a sac volva looks like — and the app draws them itself. A plate is
 * the other thing: a picture of the whole mushroom to hold a real one up against, which
 * is what the candidate page is for and what code cannot honestly produce.
 *
 * Most taxa have none, and that is the ordinary case rather than a gap to apologise for.
 * The page reads perfectly well without one.
 */
object TaxonPlate {

    /** The drawing for a taxon, or null where there is none. */
    fun of(taxonId: String): Int? = PLATES[taxonId]

    private val PLATES: Map<String, Int> = mapOf(
        "agaricus_campestris" to R.drawable.plate_agaricus_campestris,
        "amanita_bisporigera" to R.drawable.plate_amanita_bisporigera,
        "amanita_brunnescens" to R.drawable.plate_amanita_brunnescens,
        "amanita_flavoconia" to R.drawable.plate_amanita_flavoconia,
        "amanita_muscaria_guessowii" to R.drawable.plate_amanita_muscaria_guessowii,
        "amanita_phalloides" to R.drawable.plate_amanita_phalloides,
        "amanita_rubescens" to R.drawable.plate_amanita_rubescens,
        "amanita_vaginata" to R.drawable.plate_amanita_vaginata,
        "armillaria_mellea" to R.drawable.plate_armillaria_mellea,
        "armillaria_tabescens" to R.drawable.plate_armillaria_tabescens,
        "auricularia_americana" to R.drawable.plate_auricularia_americana,
        "baorangia_bicolor" to R.drawable.plate_baorangia_bicolor,
        "cantharellus_appalachiensis" to R.drawable.plate_cantharellus_appalachiensis,
        "chlorociboria_aeruginascens" to R.drawable.plate_chlorociboria_aeruginascens,
        "clavulina_cristata" to R.drawable.plate_clavulina_cristata,
        "daldinia_childiae" to R.drawable.plate_daldinia_childiae,
        "galerina_marginata" to R.drawable.plate_galerina_marginata,
        "ganoderma_applanatum" to R.drawable.plate_ganoderma_applanatum,
        "gymnopus_dryophilus" to R.drawable.plate_gymnopus_dryophilus,
        "gyromitra_caroliniana" to R.drawable.plate_gyromitra_caroliniana,
        "hygrophoropsis_aurantiaca" to R.drawable.plate_hygrophoropsis_aurantiaca,
        "inocybe_rimosa" to R.drawable.plate_inocybe_rimosa,
        "lycoperdon_perlatum" to R.drawable.plate_lycoperdon_perlatum,
        "morchella_americana" to R.drawable.plate_morchella_americana,
        "mycena_galericulata" to R.drawable.plate_mycena_galericulata,
        "paxillus_involutus" to R.drawable.plate_paxillus_involutus,
        "pleurocybella_porrigens" to R.drawable.plate_pleurocybella_porrigens,
        "psathyrella_candolleana" to R.drawable.plate_psathyrella_candolleana,
        "russula_virescens" to R.drawable.plate_russula_virescens,
        "scleroderma_citrinum" to R.drawable.plate_scleroderma_citrinum,
        "stereum_ostrea" to R.drawable.plate_stereum_ostrea,
        "trichaptum_biforme" to R.drawable.plate_trichaptum_biforme,
    )
}
