#!/usr/bin/env python3
"""
Puts the cut plates into the app, and writes the map from taxon to drawing.

The app draws its own character states — a gill running down a stem, a sac at the base —
and those are diagrams of one feature each, which is what a key needs. What code cannot
honestly draw is a *mushroom*: a plate of the destroying angel that somebody can hold a
real one up against. Those are drawn by hand or generated and cut with cut-grid.py, and
this is how they get from tools/reference/plates into the app.

Two things happen on the way in. They are reduced to one bit — the screen is one bit
deep, and a plate carrying grey is a plate carrying nothing — and they are scaled to a
width the candidate page can use, because a 1408-pixel plate is a megabyte of APK to
show at two hundred.

    python3 tools/install-plates.py            # everything in tools/reference/plates
    python3 tools/install-plates.py --dry-run

Only ids that exist in the region pack are installed; a file named after nothing is a
mistake worth being told about rather than shipping.
"""

import argparse
import glob
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
PLATES = os.path.join(HERE, "reference", "plates")
RES = os.path.join(HERE, "..", "app", "src", "main", "res", "drawable-nodpi")
KT = os.path.join(HERE, "..", "app", "src", "main", "kotlin", "com", "wanderwildwood",
                  "kinokocho", "ui", "TaxonPlate.kt")
PACK = os.path.join(HERE, "..", "app", "src", "main", "assets", "packs",
                    "southern-appalachia-v1.json")

WIDTH = 420

HEAD = '''package com.wanderwildwood.kinokocho.ui

import com.wanderwildwood.kinokocho.R

/**
 * A drawing of the whole mushroom, for the taxa that have one.
 *
 * Generated by tools/install-plates.py. Do not edit by hand.
 *
 * These are not the character drawings. Those are diagrams of one feature — how a gill
 * meets a stem, what a sac volva looks like — and the app draws them itself. A plate is
 * the other thing: a picture of the whole mushroom to hold a real one up against, which
 * is what the candidate page is for and what code cannot honestly produce.
 *
 * Most taxa have none, and that is the ordinary case rather than a gap to apologise for.
 * The page reads perfectly well without one.
 */
object TaxonPlate {

    /** The drawing for a taxon, or null where there is none. */
    fun of(taxonId: String): Int? = PLATES[taxonId]

    /** Every taxon that has one, so a test can check they are all real. */
    val ids: Set<String> get() = PLATES.keys

    private val PLATES: Map<String, Int> = mapOf(
'''

FOOT = '''    )
}
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    known = {t["id"] for t in json.load(open(PACK))["taxa"]}
    found = sorted(glob.glob(os.path.join(PLATES, "*.png")))
    if not found:
        print(f"nothing in {PLATES}")
        return

    installed, unknown = [], []
    os.makedirs(RES, exist_ok=True)
    for src in found:
        tid = os.path.splitext(os.path.basename(src))[0]
        if tid not in known:
            unknown.append(tid)
            continue
        dest = os.path.join(RES, f"plate_{tid}.png")
        if not args.dry_run:
            subprocess.run([
                "convert", src,
                "-colorspace", "Gray",
                "-resize", f"{WIDTH}x>",
                # Back to one bit after the resize, which reintroduces grey along every
                # edge. A plate that ships grey is a plate that shows as mush.
                "-threshold", "60%",
                # And the white goes transparent. The app tints these to whatever the
                # theme's ink colour is, and a tint recolours every pixel that is not
                # transparent — so a plate with an opaque white background came out as a
                # solid black rectangle, which is what it looked like on the device.
                "-transparent", "white",
                "-strip", "PNG32:" + dest,
            ], check=True)
        installed.append(tid)

    if not args.dry_run:
        with open(KT, "w") as f:
            f.write(HEAD)
            for tid in installed:
                f.write(f'        "{tid}" to R.drawable.plate_{tid},\n')
            f.write(FOOT)

    total = sum(os.path.getsize(os.path.join(RES, f"plate_{t}.png"))
                for t in installed) if not args.dry_run else 0
    print(f"{len(installed)} plates installed"
          + (f", {total // 1024} kB total" if total else " (dry run)"))
    for t in installed:
        print(f"    {t}")
    if unknown:
        print(f"\n! not in the region pack, so not installed: {', '.join(unknown)}")


if __name__ == "__main__":
    main()
