#!/usr/bin/env python3
"""
Draws the character states as line art, from real mushrooms.

On a panel with no colour, a picture of a gill attachment is not decoration — it is
the question. A reader in a wood can match a drawing against what is in their hand
faster than they can read "adnexed" and wonder whether that was the narrow one.

**Every drawing is of a named species that actually shows the character**, recorded in
EXEMPLARS below and emitted as Kotlin so the app can say what it drew. A generic
cartoon of "decurrent" teaches nothing; *Cantharellus* running down its own stem
teaches it in one look. Where a species is the textbook illustration of a character —
*Tricholoma* for a notched gill, *Amanita* for a sac volva — that is the one drawn.

What line art can carry honestly is silhouette, proportion and topology. That happens
to be exactly what these characters are: whether the gill reaches the stem, whether
the bulb has a rim, whether the tubes lift away from the cap. Colour and texture are
not attempted, because the panel has neither and the schema asks about them separately.

    python3 tools/make-art.py

Output is 96x96 vector drawables in app/src/main/res/drawable/, named
art_<character>_<value>.xml, stroke only. Drawn at about 56dp, so nothing finer than
a 3-unit gap survives — that is the constraint every drawing is built to.
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "app", "src", "main", "res", "drawable")
KT = os.path.join(HERE, "..", "app", "src", "main", "kotlin", "com",
                  "wanderwildwood", "kinokocho", "ui", "CharacterArt.kt")

STROKE = 4.0          # heavy enough to survive a slow panel and low contrast
FINE = 2.5            # gills, tubes, cross-veins: things meant to read as many
HAIR = 1.8            # texture that must not compete with the silhouette
GROUND = 86.0

# The species each drawing is taken from, and what it is doing there. Written down
# because "based on a real mushroom" is a claim that has to be checkable, and because
# a reader who wants to know why the picture looks like that deserves an answer.
EXEMPLARS = {}


def drawn_from(name, species, why):
    EXEMPLARS[name] = (species, why)
    return name


# No android:tint here: the app themes with MMD, which does not carry
# ?attr/colorOnSurface, and aapt fails on every drawable if it is set. The Icon
# composable tints these at the call site instead, which is where the theme is.
HEADER = """<!-- Generated by tools/make-art.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="96dp"
    android:height="96dp"
    android:viewportWidth="96"
    android:viewportHeight="96">
"""
FOOTER = "</vector>\n"


def path(d, width=STROKE, fill=False, cap="round"):
    return (
        '    <path\n'
        f'        android:pathData="{d}"\n'
        f'        android:strokeColor="{"#00000000" if fill else "#FF000000"}"\n'
        f'        android:strokeWidth="{0 if fill else width}"\n'
        f'        android:fillColor="{"#FF000000" if fill else "#00000000"}"\n'
        f'        android:strokeLineCap="{cap}"\n'
        '        android:strokeLineJoin="round" />\n'
    )


def write(name, species, why, *paths):
    os.makedirs(OUT, exist_ok=True)
    assert re.fullmatch(r"[a-z0-9_]+", name), name
    drawn_from(name, species, why)
    with open(os.path.join(OUT, f"{name}.xml"), "w") as f:
        f.write(HEADER + "".join(paths) + FOOTER)


# ---------------------------------------------------------------------------
# Anatomy shared between drawings, so a stem is the same stem everywhere.

def ground(x1=10, x2=86, y=GROUND):
    return path(f"M{x1},{y} L{x2},{y}", width=FINE)


def stem_sides(x=48, top=48, bottom=GROUND, half=6):
    return f"M{x - half},{top} L{x - half},{bottom} M{x + half},{top} L{x + half},{bottom}"


def capped_cap(cx=48, half=34, base=46, rise=24, flesh=5):
    """
    A cap in section, with thickness.

    Cap flesh is not a line: gills hang from a wedge of tissue, and drawing it as one
    line is what makes amateur diagrams look wrong. The lower curve is where the gills
    attach, the upper is the surface.
    """
    return (
        f"M{cx - half},{base} "
        f"Q{cx - half},{base - rise} {cx},{base - rise} "
        f"Q{cx + half},{base - rise} {cx + half},{base} "
        f"Q{cx + half - 4},{base - flesh} {cx + half - 10},{base - flesh + 1} "
        f"L{cx - half + 10},{base - flesh + 1} "
        f"Q{cx - half + 4},{base - flesh} {cx - half},{base} Z"
    )


def tilted_cap(cx=48, cy=52, rx=34, ry=13, rise=22):
    """
    A cap seen from below and in front, so the underside is a surface and not an edge.

    Which of gills, tubes, pores, teeth or ridges a mushroom has is decided by looking
    underneath. Drawn in profile the answer is a few pixels of texture on a line; tilted,
    it is most of the picture. Field guides tilt for exactly this reason.
    """
    return path(
        f"M{cx - rx},{cy} "
        f"Q{cx - rx},{cy - rise} {cx},{cy - rise} "
        f"Q{cx + rx},{cy - rise} {cx + rx},{cy} "
        f"Q{cx + rx},{cy + ry} {cx},{cy + ry} "
        f"Q{cx - rx},{cy + ry} {cx - rx},{cy} Z"
    )


def underside_rim(cx=48, cy=52, rx=34, ry=13):
    """The ellipse where the cap edge meets the underside — the near edge only."""
    return path(
        f"M{cx - rx},{cy} Q{cx - rx},{cy + ry} {cx},{cy + ry} Q{cx + rx},{cy + ry} {cx + rx},{cy}",
        width=FINE,
    )


def radiating(cx=48, cy=52, rx=34, ry=13, n=13, inner=0.18, width=FINE):
    """
    Gills or ridges on a tilted underside: lines from the centre out to the rim.

    Foreshortened by the same ellipse as the rim, so they sit on the surface rather
    than floating over it.
    """
    import math
    d = []
    for i in range(n):
        # Only the front half is visible; the back is hidden by the cap.
        t = math.pi * (i / (n - 1))
        x = cx + rx * math.cos(t) * -1
        y = cy + ry * math.sin(t)
        xi = cx + (x - cx) * inner
        yi = cy + (y - cy) * inner
        d.append(f"M{xi:.1f},{yi:.1f} L{x:.1f},{y:.1f}")
    return path(" ".join(d), width=width)


def pore_field(cx=48, cy=54, rx=30, ry=10, rows=3, per=7, r=2.6, fine=False):
    """Round tube mouths on a tilted underside — a bolete's, drawn big enough to count."""
    import math
    d = []
    for j in range(rows):
        fy = (j + 1) / (rows + 0.6)
        for i in range(per):
            ft = (i + 0.5) / per
            x = cx - rx + 2 * rx * ft
            span = math.sqrt(max(0.0, 1 - ((x - cx) / rx) ** 2))
            y = cy + ry * fy * span
            rr = r * (0.75 + 0.25 * span)
            d.append(
                f"M{x - rr:.1f},{y:.1f} "
                f"Q{x - rr:.1f},{y - rr:.1f} {x:.1f},{y - rr:.1f} "
                f"Q{x + rr:.1f},{y - rr:.1f} {x + rr:.1f},{y:.1f} "
                f"Q{x + rr:.1f},{y + rr:.1f} {x:.1f},{y + rr:.1f} "
                f"Q{x - rr:.1f},{y + rr:.1f} {x - rr:.1f},{y:.1f} Z"
            )
    return path(" ".join(d), width=HAIR if fine else FINE)


def gill_blades(cx=48, half=34, base=45, depth=10, n=8, inner=12, taper=True):
    """
    Gills seen edge-on under a cap. They are deepest at mid-radius and shallow at the
    margin, which is what makes a gilled underside read as gills and not as a comb.
    """
    d = []
    step = (half - inner) / max(n - 1, 1)
    for i in range(n):
        off = inner + i * step
        frac = 1.0 - (off - inner) / max(half - inner, 1)
        dep = depth * (0.45 + 0.55 * frac) if taper else depth
        for sign in (-1, 1):
            x = cx + sign * off
            d.append(f"M{x:.1f},{base} L{x:.1f},{base + dep:.1f}")
    return path(" ".join(d), width=FINE)


# ---------------------------------------------------------------------------
# fruitbody_type — MycoKey's top-level split. Asked first, always.

def fruitbody_type():
    c = "fruitbody_type"

    # The first four are all decided by one look underneath, so all four are tilted to
    # put that surface where the eye lands. They differ only in what is on it.

    write(f"art_{c}_gilled_stemmed",
          "Agaricus campestris",
          "Underneath: blades radiating from the stem, thin and sharp-edged.",
          tilted_cap(),
          radiating(n=15),
          underside_rim(),
          path("M42,60 L42,86 M54,60 L54,86"),
          ground())

    # The tube layer is a mat of its own thickness, and the stem of a bolete is fat —
    # both are how you tell it from a gilled mushroom before you even look closely.
    write(f"art_{c}_bolete",
          "Boletus edulis",
          "Underneath: round tube mouths in a thick soft layer; the stem is stout.",
          path("M14,42 Q14,20 48,20 Q82,20 82,42 Q82,47 76,48 L20,48 Q14,47 14,42 Z"),
          path("M20,48 Q48,54 76,48 Q76,58 48,62 Q20,58 20,48 Z"),
          path("M27,52 Q27,49 30,49 Q33,49 33,52 Q33,55 30,55 Q27,55 27,52 Z "
               "M37,54 Q37,51 40,51 Q43,51 43,54 Q43,57 40,57 Q37,57 37,54 Z "
               "M47,55 Q47,52 50,52 Q53,52 53,55 Q53,58 50,58 Q47,58 47,55 Z "
               "M57,54 Q57,51 60,51 Q63,51 63,54 Q63,57 60,57 Q57,57 57,54 Z "
               "M66,51 Q66,48 69,48 Q72,48 72,51 Q72,54 69,54 Q66,54 66,51 Z",
               width=HAIR),
          path("M36,62 Q30,72 32,86 L64,86 Q66,72 60,62"),
          path("M35,70 Q48,74 62,70 M33,78 Q48,82 63,78", width=HAIR),
          ground())

    write(f"art_{c}_polypore",
          "Trametes versicolor",
          "Underneath: pores far finer than a bolete's, on a tough bracket with no stem.",
          path("M14,10 L14,86"),
          path("M14,36 Q44,26 80,42 Q80,52 76,54 Q44,46 14,54 Z"),
          path("M20,40 Q46,33 72,45 M24,45 Q48,39 76,50", width=HAIR),
          path("M20,54 Q46,48 74,58 Q46,58 20,60 Z"),
          pore_field(cx=46, cy=55, rx=24, ry=4, rows=2, per=9, r=1.5, fine=True))

    write(f"art_{c}_toothed",
          "Hydnum repandum",
          "Underneath: soft spines hanging down, not blades and not pores.",
          tilted_cap(rx=32, ry=11, rise=18),
          path("M18,54 L19,66 M24,57 L25,70 M30,59 L31,73 M36,61 L37,75 M42,62 L43,76 "
               "M48,62 L49,77 M54,62 L55,76 M60,61 L61,74 M66,59 L67,71 M72,56 L73,67 "
               "M78,53 L79,63", width=FINE),
          path("M42,62 Q41,74 42,86 M56,62 Q57,74 56,86"),
          ground())

    write(f"art_{c}_chanterelle_like",
          "Cantharellus lateritius",
          "Underneath: blunt forking ridges, thick and rounded where a gill is thin.",
          path("M12,32 Q22,20 32,28 Q42,18 50,26 Q60,17 70,27 Q82,20 86,34 "
               "Q76,44 66,50 L58,72 Q54,82 52,88 L44,88 Q42,78 38,70 L30,48 "
               "Q18,42 12,32 Z"),
          path("M24,36 Q30,50 34,62 M36,34 Q40,50 42,66 M50,32 Q50,50 49,68 "
               "M63,34 Q58,50 55,64 M74,36 Q66,46 62,54", width=STROKE),
          path("M28,44 Q31,48 34,44 M44,42 Q47,46 50,42 M55,46 Q58,50 61,46",
               width=FINE),
          ground(30, 66))

    write(f"art_{c}_coral_club",
          "Ramaria stricta",
          "Repeatedly forking upright branches from a common base, no cap anywhere.",
          path("M48,86 L48,60"),
          path("M48,60 Q40,50 34,38 M48,60 Q56,50 62,38 M48,62 Q46,48 44,34 "
               "M48,62 Q52,48 54,34"),
          path("M34,38 L28,24 M34,38 L36,22 M62,38 L60,22 M62,38 L68,24 "
               "M44,34 L40,20 M44,34 L46,18 M54,34 L52,18 M56,34 L60,20", width=FINE),
          ground(24, 72))

    # Lycoperdon: the sterile base is what separates a puffball from a ball of anything
    # else, and the apical pore is where the spores actually leave.
    write(f"art_{c}_gasteroid",
          "Lycoperdon perlatum",
          "Spores formed inside; sterile base tapering to the ground, pore at the top.",
          path("M30,50 Q30,28 48,28 Q66,28 66,50 Q66,62 62,70 "
               "Q60,80 54,86 L42,86 Q36,80 34,70 Q30,62 30,50 Z"),
          path("M44,30 Q48,26 52,30", width=FINE),
          path("M37,42 L39,44 M46,38 L48,40 M56,42 L58,44 M40,54 L42,56 M54,54 L56,56",
               width=HAIR),
          ground())

    write(f"art_{c}_cup_disc",
          "Peziza badia",
          "An ascomycete cup, sessile, hymenium on the inner face.",
          path("M18,40 Q18,74 48,74 Q78,74 78,40"),
          path("M18,40 Q48,28 78,40 Q48,50 18,40 Z"),
          path("M30,46 Q48,54 66,46", width=HAIR),
          ground(14, 82))

    write(f"art_{c}_resupinate",
          "Stereum ostrea",
          "A crust lying flat on wood, edge lifting only slightly.",
          path("M12,74 L84,74"),
          path("M20,74 Q22,58 34,60 Q46,46 60,58 Q76,56 78,74"),
          path("M24,70 Q28,64 34,66 M44,60 Q50,56 56,62 M62,64 Q68,62 72,70", width=HAIR),
          path("M20,74 Q18,70 16,72 M78,74 Q80,70 82,72", width=FINE))

    write(f"art_{c}_jelly",
          "Tremella mesenterica",
          "Gelatinous folded lobes with no cap, stem, gills or pores anywhere.",
          path("M16,60 Q14,44 26,40 Q30,26 42,32 Q50,22 58,32 Q70,26 74,38 "
               "Q86,44 82,60 Q80,74 60,78 Q34,82 22,72 Q16,68 16,60 Z"),
          path("M24,50 Q32,42 36,52 Q40,62 48,54 Q54,48 58,58 Q64,66 72,56",
               width=FINE),
          path("M28,66 Q36,58 42,68 Q50,76 58,68 Q64,62 70,68", width=FINE),
          path("M10,84 L86,84", width=FINE))

    write(f"art_{c}_flask",
          "Hypoxylon fragiforme",
          "A hard cushion on wood, cut to show flask-shaped chambers with necks to the surface.",
          path("M10,78 L86,78", width=FINE),
          path("M20,78 Q18,48 34,42 Q50,36 64,44 Q78,52 76,78 Z"),
          path("M30,60 Q30,53 35,53 Q40,53 40,60 Q40,67 35,67 Q30,67 30,60 Z", width=FINE),
          path("M46,64 Q46,56 51,56 Q56,56 56,64 Q56,71 51,71 Q46,71 46,64 Z", width=FINE),
          path("M60,58 Q60,52 64,52 Q68,52 68,58 Q68,64 64,64 Q60,64 60,58 Z", width=FINE),
          path("M35,53 L34,45 M51,56 L53,44 M64,52 L67,46", width=HAIR),
          path("M33,44 L35,43 M52,43 L54,42 M66,45 L68,44", width=FINE))

    write(f"art_{c}_other",
          "—",
          "Not a taxon: the honest exit when nothing above fits.",
          path("M48,26 Q66,26 66,42 Q66,54 48,58 L48,66"),
          path("M48,76 L48,78", width=6))


# ---------------------------------------------------------------------------
# gill_attachment — one frame, one thing moving. iNaturalist field 917 verbatim.

def gill_attachment():
    """
    A vertical section, cut so the junction is the biggest thing in the picture.

    The first attempt drew a whole mushroom with hanging gills, and all six states came
    out identical: where the gill meets the stem is a few pixels, and it vanished. So
    the drawing is zoomed to the junction, the stem is drawn wide enough to be a target,
    and the gill that tells the story is filled solid while its neighbours are outlines.
    """
    c = "gill_attachment"

    def cap():
        # Cap in section, its underside flat at y=38 so gills hang from a straight line.
        return path("M6,38 Q48,10 90,38 Q48,30 6,38 Z")

    def stem(top=38, bottom=90):
        return path(f"M38,{top} L38,{bottom} M58,{top} L58,{bottom}")

    def outer_gills():
        # Neighbours, kept thin so the solid one carries the eye.
        return path("M12,38 L12,52 M19,38 L19,53 M26,38 L26,54 "
                    "M70,38 L70,54 M77,38 L77,53 M84,38 L84,52", width=FINE)

    write(f"art_{c}_free",
          "Agaricus campestris",
          "The gill stops short of the stem: a clear gap runs all the way round.",
          cap(), outer_gills(),
          path("M30,38 L34,38 L34,55 L30,55 Z", fill=True),
          path("M62,38 L66,38 L66,55 L62,55 Z", fill=True),
          stem(),
          # The gap is the character, so it is called out with its own arrow.
          path("M34,46 L38,46 M62,46 L58,46", width=HAIR),
          path("M36,44 L38,46 L36,48 M60,44 L58,46 L60,48", width=HAIR))

    write(f"art_{c}_adnexed",
          "Mycena galericulata",
          "The gill touches the stem, but over only the top of its depth.",
          cap(), outer_gills(),
          path("M30,38 L38,38 L38,44 L34,55 L30,55 Z", fill=True),
          path("M66,38 L58,38 L58,44 L62,55 L66,55 Z", fill=True),
          stem())

    write(f"art_{c}_adnate",
          "Gymnopus dryophilus",
          "The gill meets the stem squarely, over its whole depth.",
          cap(), outer_gills(),
          path("M30,38 L38,38 L38,55 L30,55 Z", fill=True),
          path("M66,38 L58,38 L58,55 L66,55 Z", fill=True),
          stem())

    write(f"art_{c}_notched",
          "Tricholoma sejunctum",
          "The gill runs in deep, then is cut away sharply just before the stem.",
          cap(), outer_gills(),
          path("M30,38 L38,38 L38,42 L34,48 L34,57 L30,57 Z", fill=True),
          path("M66,38 L58,38 L58,42 L62,48 L62,57 L66,57 Z", fill=True),
          stem())

    write(f"art_{c}_decurrent",
          "Cantharellus lateritius",
          "The gill does not stop at the stem — it turns and runs down the outside of it.",
          cap(), outer_gills(),
          path("M30,38 L38,38 L38,70 L34,70 L34,52 L30,50 Z", fill=True),
          path("M66,38 L58,38 L58,70 L62,70 L62,52 L66,50 Z", fill=True),
          stem(bottom=90))

    write(f"art_{c}_no_stem",
          "Pleurotus ostreatus",
          "Attached to the wood at one side, so there is no stem for a gill to meet.",
          path("M86,14 L86,88", width=FINE),
          path("M86,34 Q48,14 8,32 Q46,40 86,40 Z"),
          path("M14,34 L17,50 M22,35 L25,53 M30,36 L33,55 M38,37 L41,56 "
               "M46,38 L49,57 M54,38 L57,56 M62,39 L65,54 M70,39 L72,51",
               width=FINE),
          path("M78,40 L86,40 L86,52 L80,50 Z", fill=True))


# ---------------------------------------------------------------------------
# stipe_base — where the volva lives. These carry more weight than any other set.

def stipe_base():
    c = "stipe_base"
    top = path("M36,12 L36,40 M60,12 L60,40")

    write(f"art_{c}_equal",
          "Agaricus campestris",
          "The same width all the way down, ending flat in the soil.",
          top, path("M36,40 L36,80 M60,40 L60,80"), ground(22, 74, 80))

    write(f"art_{c}_bulbous",
          "Cortinarius alboviolaceus",
          "A stem that swells smoothly into a bulb, with no rim where it widens.",
          top,
          path("M36,40 Q34,58 28,66 Q28,78 48,79 Q68,78 68,66 Q62,58 60,40"),
          ground(18, 78, 80))

    # Amanita citrina: abruptly bulbous with a distinct gutter. The rim is the whole
    # character, so it is drawn as a hard shoulder rather than a curve.
    write(f"art_{c}_marginate",
          "Amanita citrina",
          "A bulb with a distinct rim and gutter where the stem meets it.",
          top,
          path("M36,40 L36,58 L26,62 L24,72 Q24,80 48,81 Q72,80 72,72 L70,62 L60,58 L60,40"),
          path("M24,66 Q48,71 72,66", width=FINE),
          ground(16, 80, 82))

    # The one drawing in the app that most needs to be right. A membranous sac with a
    # free upper limb, the stem rising cleanly out of it.
    write(f"art_{c}_sac_volva",
          "Amanita bisporigera",
          "A membranous bag with a free rim; the stem stands inside it, not fused to it.",
          top,
          path("M36,40 L36,66 M60,40 L60,66"),
          path("M28,56 Q22,70 24,79 Q30,86 48,86 Q66,86 72,79 Q74,70 68,56"),
          path("M28,56 Q32,63 36,66 M68,56 Q64,63 60,66"),
          path("M30,60 Q34,64 36,64 M66,60 Q62,64 60,64", width=HAIR),
          ground(14, 82, 88))

    write(f"art_{c}_volva_rings",
          "Amanita muscaria",
          "No bag — the volva left concentric rings of scales around a bulb.",
          top,
          path("M36,40 Q34,56 30,62 Q28,76 48,82 Q68,76 66,62 Q62,56 60,40"),
          path("M29,66 Q48,73 67,66 M30,72 Q48,79 66,72 M32,60 Q48,66 64,60", width=FINE),
          ground(18, 78, 86))

    write(f"art_{c}_rooting",
          "Hymenopellis radicata",
          "A pseudorhiza: the stem carries on below the soil as a long tapering root.",
          top,
          path("M36,40 L38,60 Q44,74 46,94 M60,40 L58,60 Q52,74 50,94"),
          path("M12,60 L84,60", width=FINE),
          path("M20,66 L28,66 M52,68 L62,68 M70,66 L78,66", width=HAIR))

    write(f"art_{c}_tapering",
          "Entoloma abortivum",
          "Narrowing steadily downwards, without ever swelling.",
          top, path("M36,40 L43,80 M60,40 L53,80"), ground(22, 74, 80))

    write(f"art_{c}_rhizomorphs",
          "Armillaria mellea",
          "Cords of mycelium leaving the base and running off through the substrate.",
          top,
          path("M36,40 L36,72 M60,40 L60,72"),
          path("M36,72 Q24,76 12,74 M38,74 Q28,84 16,86 M60,72 Q72,76 84,74 "
               "M58,74 Q68,84 80,86 M48,74 L48,86", width=FINE),
          ground(10, 86, 72))

    write(f"art_{c}_buried",
          "—",
          "Not a mushroom: the base was left in the ground, which is the commonest miss.",
          top,
          path("M36,40 L36,60 M60,40 L60,60"),
          path("M10,60 L86,60"),
          path("M18,68 L26,68 M34,68 L42,68 M50,68 L58,68 M66,68 L74,68 "
               "M22,76 L30,76 M38,76 L46,76 M54,76 L62,76 M26,84 L34,84 M50,84 L58,84",
               width=HAIR))


# ---------------------------------------------------------------------------
# cap_shape — the standard series, each on a species that holds that shape.

def cap_shape():
    c = "cap_shape"
    st = path("M44,64 L44,86 M52,64 L52,86")

    write(f"art_{c}_egg", "Coprinus comatus",
          "Taller than wide, sides near-parallel, before any expansion.",
          path("M32,68 Q30,22 48,20 Q66,22 64,68"),
          path("M44,68 L44,86 M52,68 L52,86"), ground())

    write(f"art_{c}_conical", "Hygrocybe conica",
          "Straight sides meeting at a point; never flattening with age.",
          path("M22,66 L48,18 L74,66 Q48,72 22,66 Z"), st, ground())

    write(f"art_{c}_bell", "Panaeolus papilionaceus",
          "Sides curve out and hang down: a bell, not a cone.",
          path("M24,66 Q24,24 48,24 Q72,24 72,66 Q48,72 24,66 Z"), st, ground())

    write(f"art_{c}_convex", "Agaricus campestris",
          "An even dome, the margin still turned down.",
          path("M16,58 Q16,30 48,30 Q80,30 80,58 Q48,66 16,58 Z"), st, ground())

    write(f"art_{c}_flat", "Russula virescens",
          "Expanded flat, the margin level with the centre.",
          path("M14,52 Q48,42 82,52 Q48,62 14,52 Z"), st, ground())

    write(f"art_{c}_depressed", "Lactarius deliciosus",
          "Flat, but sunk in the middle — not yet a funnel.",
          path("M14,50 Q28,40 44,50 Q48,54 52,50 Q68,40 82,50 Q48,62 14,50 Z"),
          st, ground())

    write(f"art_{c}_funnel", "Clitocybe gibba",
          "The whole cap slopes into the stem; the hollow reaches the flesh.",
          path("M14,38 Q30,36 42,58 L54,58 Q66,36 82,38 Q48,68 14,38 Z"),
          path("M44,58 L44,86 M52,58 L52,86"), ground())

    write(f"art_{c}_umbonate", "Amanita parcivolvata",
          "A broad cap with a distinct raised boss at the centre.",
          path("M14,56 Q28,44 40,42 Q44,28 48,26 Q52,28 56,42 Q68,44 82,56 "
               "Q48,64 14,56 Z"), st, ground())

    write(f"art_{c}_umbilicate", "Arrhenia epichysium",
          "A small sharp navel at the centre of an otherwise flat cap.",
          path("M14,50 Q30,38 42,46 L46,56 L50,56 L54,46 Q66,38 82,50 Q48,60 14,50 Z"),
          st, ground())


# ---------------------------------------------------------------------------

def ring():
    c = "ring"
    cap = path("M14,32 Q48,10 82,32 Q80,37 74,37 L22,37 Q14,37 14,32 Z")
    st = "M42,37 L42,86 M54,37 L54,86"

    write(f"art_{c}_absent", "Russula virescens",
          "No veil, so no ring is ever left behind.",
          cap, path(st))

    write(f"art_{c}_skirt", "Amanita bisporigera",
          "A membranous veil torn free at the margin and left hanging as a skirt.",
          cap, path(st),
          path("M42,52 Q28,54 24,66 Q34,72 48,70 Q62,72 72,66 Q68,54 54,52"),
          path("M32,62 Q40,66 48,66 Q56,66 64,62", width=HAIR))

    write(f"art_{c}_zone", "Cortinarius armillatus",
          "A cortina leaves no membrane, only a fibrous band where it broke.",
          cap, path(st),
          path("M42,56 L34,55 M54,56 L62,55 M42,60 L36,60 M54,60 L60,60 "
               "M42,52 L37,51 M54,52 L59,51", width=HAIR))

    write(f"art_{c}_movable", "Amanita jacksonii",
          "A free collar that slides on the stem rather than gripping it.",
          cap, path(st),
          path("M30,58 Q48,50 66,58 Q48,66 30,58 Z"),
          path("M26,52 L20,47 M70,52 L76,47", width=FINE),
          path("M24,58 L18,58 M72,58 L78,58", width=HAIR))

    write(f"art_{c}_cannot_tell", "—",
          "Not a state of the mushroom: the specimen is too old or too damaged to say.",
          cap, path(st),
          path("M40,54 L34,56 M56,55 L62,58", width=HAIR),
          path("M48,74 Q60,74 60,65 Q60,59 48,59"),
          path("M48,84 L48,86", width=6))


def stipe_presence():
    c = "stipe_presence"

    write(f"art_{c}_central", "Agaricus campestris",
          "The stem meets the cap at its centre.",
          path(capped_cap(base=48, rise=22)), gill_blades(base=47, depth=8),
          path("M42,47 L42,86 M54,47 L54,86"), ground())

    write(f"art_{c}_off_centre", "Pluteus petasatus",
          "The stem meets the cap away from the centre, but not at the edge.",
          path(capped_cap(base=48, rise=22)), gill_blades(base=47, depth=8),
          path("M26,47 L26,86 M38,47 L38,86"), ground())

    write(f"art_{c}_lateral", "Panellus stipticus",
          "A short stem at the very edge, against the wood.",
          path("M84,14 L84,86", width=FINE),
          path("M84,40 Q54,26 22,42 Q20,48 26,50 Q56,50 84,48 Z"),
          path("M26,50 L28,58 M34,50 L36,60 M42,50 L44,60 M50,50 L52,59 "
               "M58,50 L60,57", width=HAIR),
          path("M70,50 L70,60 M80,49 L80,60"))

    write(f"art_{c}_absent_attached", "Pleurotus ostreatus",
          "Joined straight to the wood with no stem at all.",
          path("M86,12 L86,84", width=FINE),
          path("M86,36 Q54,18 12,34 Q10,41 16,43 Q54,43 86,45 Z"),
          path("M18,42 L21,56 M27,42 L30,59 M36,43 L39,61 M45,43 L48,61 "
               "M54,43 L57,59 M63,43 L65,56", width=HAIR))

    write(f"art_{c}_absent_sitting", "Lycoperdon perlatum",
          "Sitting on the substrate, attached only by cords.",
          path("M24,56 Q24,32 48,32 Q72,32 72,56 Q72,72 48,76 Q24,72 24,56 Z"),
          path("M40,60 Q34,72 30,78 M56,60 Q62,72 66,78", width=HAIR),
          ground(14, 82, 78))


def gill_spacing():
    c = "gill_spacing"
    cap = path("M10,34 Q48,14 86,34 Q84,39 78,39 L18,39 Q10,39 10,34 Z")
    for name, n, species, why in (
        ("crowded", 17, "Marasmius oreades",
         "So many that the eye cannot separate them at the margin."),
        ("close", 10, "Agaricus campestris", "Regularly spaced, distinct, not touching."),
        ("distant", 5, "Omphalotus illudens",
         "Few and well apart, with cap flesh visible between."),
    ):
        d = []
        for i in range(n):
            x = 13 + i * (70 / (n - 1))
            frac = 1 - abs(x - 48) / 40
            d.append(f"M{x:.1f},39 L{x:.1f},{39 + 12 + 14 * frac:.1f}")
        write(f"art_{c}_{name}", species, why, cap, path(" ".join(d), width=FINE))


def growth_habit():
    c = "growth_habit"

    def little(x, y, half=12, rise=9, stem_len=17):
        return (f"M{x - half},{y} Q{x - half},{y - rise} {x},{y - rise} "
                f"Q{x + half},{y - rise} {x + half},{y} Z "
                f"M{x - 3},{y} L{x - 3},{y + stem_len} M{x + 3},{y} L{x + 3},{y + stem_len}")

    write(f"art_{c}_single", "Amanita bisporigera",
          "One fruitbody, alone.",
          path(little(48, 60)), ground(22, 74))

    write(f"art_{c}_few", "Boletus edulis",
          "A few, each with its own base, not touching.",
          path(little(28, 62) + " " + little(66, 58)), ground())

    write(f"art_{c}_troop", "Marasmius oreades",
          "Many scattered across the ground, unconnected.",
          path(little(18, 50, 8, 6, 12) + " " + little(44, 62, 11, 8, 16) + " " +
               little(72, 48, 8, 6, 12) + " " + little(58, 36, 7, 5, 10)),
          ground())

    write(f"art_{c}_caespitose", "Armillaria mellea",
          "Clustered, the bases crowded together but still separate.",
          path(little(32, 52, 11, 8, 22) + " " + little(60, 48, 11, 8, 26) + " " +
               little(46, 62, 11, 8, 16)),
          ground(22, 74))

    write(f"art_{c}_fused", "Omphalotus illudens",
          "Bases run together into one mass — you cannot pull one out alone.",
          path(little(32, 48, 11, 8, 0) + " " + little(60, 46, 11, 8, 0)),
          path("M30,48 Q36,62 40,80 M62,46 Q58,62 56,80 M44,52 L46,80 M52,52 L50,80"),
          path("M38,80 Q48,84 58,80"),
          ground(24, 72))

    write(f"art_{c}_ring", "Marasmius oreades",
          "A fairy ring: the arc of an outward-growing mycelium.",
          path("M18,64 Q48,50 78,64 Q48,78 18,64 Z", width=FINE),
          path("M24,58 L24,50 M40,54 L40,46 M56,54 L56,46 M72,58 L72,50 "
               "M32,72 L32,64 M64,72 L64,64", width=FINE))

    write(f"art_{c}_tiered", "Trametes versicolor",
          "Shelving in overlapping tiers up a trunk.",
          path("M16,12 L16,86"),
          path("M16,28 Q38,22 58,34 Q38,40 16,38 Z"),
          path("M16,48 Q42,42 66,54 Q42,60 16,58 Z"),
          path("M16,68 Q36,64 54,72 Q36,78 16,76 Z"))


def cap_margin():
    c = "cap_margin"
    body = path("M14,50 Q48,24 82,50")

    write(f"art_{c}_inrolled", "Paxillus involutus",
          "Rolled right under, so the edge points back at the stem.",
          body, path("M14,50 Q6,60 16,66 Q26,62 20,52 M82,50 Q90,60 80,66 Q70,62 76,52"))
    write(f"art_{c}_incurved", "Agaricus campestris",
          "Curved inwards but not rolled.",
          body, path("M14,50 Q12,62 24,65 M82,50 Q84,62 72,65"))
    write(f"art_{c}_straight", "Russula virescens",
          "Meeting the cap surface at a straight edge.",
          body, path("M14,50 L14,64 M82,50 L82,64"))
    write(f"art_{c}_uplifted", "Clitocybe gibba",
          "Turned up with age, exposing the gills from the side.",
          path("M14,42 Q34,60 48,42 Q62,60 82,42"),
          path("M44,44 L44,82 M52,44 L52,82"))
    write(f"art_{c}_wavy", "Cantharellus lateritius",
          "Irregularly lobed and waved rather than circular.",
          path("M12,52 Q22,40 32,52 Q42,64 52,52 Q62,40 72,52 Q78,58 84,52"),
          path("M44,58 L44,84 M52,58 L52,84"))
    write(f"art_{c}_striate", "Amanita parcivolvata",
          "Grooved at the edge, following the gills beneath.",
          body, path("M20,54 L18,64 M30,49 L29,61 M40,46 L40,59 M56,46 L56,59 "
                     "M66,49 L67,61 M76,54 L78,64", width=HAIR))
    write(f"art_{c}_translucent_striate", "Mycena galericulata",
          "Flesh thin enough that the gills show through as lines.",
          body,
          path("M18,54 L16,66 M28,49 L27,63 M38,46 L38,61 M48,44 L48,60 "
               "M58,46 L58,61 M68,49 L69,63 M78,54 L80,66", width=HAIR),
          path("M38,72 L58,72 M44,78 L52,78", width=HAIR))
    write(f"art_{c}_appendiculate", "Coprinus comatus",
          "Fragments of the veil left hanging from the edge.",
          body,
          path("M18,54 Q20,62 16,66 M30,50 Q32,60 28,65 M42,47 Q44,58 40,64 "
               "M54,47 Q56,58 52,64 M66,50 Q68,60 64,65 M78,55 Q80,63 76,67",
               width=HAIR))


def veil_remnants():
    c = "veil_remnants"
    body = path("M14,52 Q48,24 82,52 Q80,57 74,57 L22,57 Q14,57 14,52 Z")
    st = path("M44,57 L44,86 M52,57 L52,86")

    write(f"art_{c}_none", "Russula virescens",
          "Nothing on the cap: there was no universal veil to leave anything.",
          body, st)
    write(f"art_{c}_warts", "Amanita muscaria",
          "Loose warts of universal veil, easily rubbed or washed off.",
          body, st,
          path("M30,44 Q34,39 39,44 Q34,49 30,44 Z M44,34 Q49,29 54,34 Q49,39 44,34 Z "
               "M58,42 Q63,37 68,42 Q63,47 58,42 Z M22,50 Q26,46 30,50 Q26,54 22,50 Z "
               "M68,50 Q72,46 76,50 Q72,54 68,50 Z"))
    write(f"art_{c}_single_patch", "Amanita parcivolvata",
          "One large sheet of veil left sitting on the cap.",
          body, st,
          path("M34,34 Q48,25 64,36 Q58,49 42,47 Z"),
          path("M42,38 Q50,36 56,40", width=HAIR))
    write(f"art_{c}_fibrous_scales", "Pholiota squarrosa",
          "Recurved scales that are part of the cap skin, not loose patches.",
          body, st,
          path("M26,50 Q30,42 34,46 M38,44 Q42,35 46,40 M52,38 Q56,33 58,42 "
               "M62,42 Q67,36 70,46 M32,54 Q36,48 40,52 M56,52 Q60,46 64,53",
               width=HAIR))
    write(f"art_{c}_peeling_skin", "Pluteus petasatus",
          "A cuticle lifting and peeling back from the margin.",
          body, st,
          path("M14,52 Q26,42 36,50 Q30,60 18,60"),
          path("M20,54 Q26,50 32,53", width=HAIR))


def gill_edge():
    c = "gill_edge"

    def face():
        return path("M16,26 L16,64 M80,26 L80,64 M16,26 L80,26", width=FINE)

    write(f"art_{c}_even", "Agaricus campestris",
          "A clean straight edge, seen face-on.",
          face(), path("M16,64 L80,64"))
    write(f"art_{c}_serrate", "Lentinellus ursinus",
          "Regularly toothed, like a saw.",
          face(),
          path("M16,64 L22,57 L28,64 L34,57 L40,64 L46,57 L52,64 L58,57 "
               "L64,64 L70,57 L76,64 L80,60"))
    write(f"art_{c}_wavy", "Pleurotus ostreatus",
          "Undulating without discrete teeth.",
          face(), path("M16,62 Q26,52 36,62 Q46,72 56,62 Q66,52 76,62 Q79,64 80,63"))
    write(f"art_{c}_different_colour", "Mycena galericulata",
          "The edge is pigmented differently from the gill face.",
          face(), path("M16,60 L80,60 L80,68 L16,68 Z", fill=True))


def stipe_flesh():
    c = "stipe_flesh"

    def outer():
        return path("M32,10 L32,84 M64,10 L64,84 M32,84 Q48,88 64,84")

    write(f"art_{c}_solid", "Boletus edulis",
          "Filled right through with unbroken flesh.",
          outer(),
          path("M37,20 L59,42 M37,36 L59,58 M37,52 L59,74 M37,68 L53,84 M45,16 L59,30",
               width=HAIR))
    write(f"art_{c}_stuffed", "Agaricus campestris",
          "A softer pith down the middle, distinct from the wall.",
          outer(),
          path("M40,14 Q47,28 40,42 Q47,56 40,70 Q46,79 42,84 "
               "M56,14 Q49,28 56,42 Q49,56 56,70 Q50,79 54,84", width=FINE))
    write(f"art_{c}_hollow", "Marasmius oreades",
          "An open tube: the wall is all there is.",
          outer(), path("M40,12 L40,84 M56,12 L56,84"))
    write(f"art_{c}_chambered", "Coprinus comatus",
          "Cross-walls dividing the hollow into chambers.",
          outer(),
          path("M40,12 L40,84 M56,12 L56,84"),
          path("M40,30 Q48,34 56,30 M40,48 Q48,52 56,48 M40,66 Q48,70 56,66", width=FINE))


def gill_extras():
    c = "gill_extras"

    def cap():
        return path("M10,30 Q48,12 86,30 Q84,35 78,35 L18,35 Q10,35 10,30 Z")

    write(f"art_{c}_lamellulae", "Agaricus campestris",
          "Short gills starting at the margin, not reaching the stem.",
          cap(),
          path("M14,35 L14,68 M26,35 L26,68 M38,35 L38,68 M50,35 L50,68 "
               "M62,35 L62,68 M74,35 L74,68", width=FINE),
          path("M20,35 L20,52 M32,35 L32,52 M44,35 L44,52 M56,35 L56,52 "
               "M68,35 L68,52 M80,35 L80,52", width=HAIR))
    write(f"art_{c}_forked", "Russula virescens",
          "Gills dividing in two on their way to the margin.",
          cap(),
          path("M18,35 L18,50 Q18,58 13,68 M18,50 Q18,58 24,68 "
               "M40,35 L40,50 Q40,58 35,68 M40,50 Q40,58 46,68 "
               "M62,35 L62,50 Q62,58 57,68 M62,50 Q62,58 68,68 "
               "M80,35 L80,68 M30,35 L30,68 M52,35 L52,68", width=FINE))
    write(f"art_{c}_veined", "Cantharellus lateritius",
          "Cross-veins bridging between the ridges.",
          cap(),
          path("M16,35 L16,68 M30,35 L30,68 M44,35 L44,68 M58,35 L58,68 "
               "M72,35 L72,68", width=FINE),
          path("M16,46 Q23,52 30,46 Q37,52 44,46 Q51,52 58,46 Q65,52 72,46 "
               "M16,58 Q23,63 30,58 Q37,63 44,58 Q51,63 58,58", width=HAIR))


def cap_colour_pattern():
    c = "cap_colour_pattern"

    def rim():
        return path("M48,16 Q80,16 80,48 Q80,80 48,80 Q16,80 16,48 Q16,16 48,16 Z")

    write(f"art_{c}_uniform", "Russula virescens",
          "One tone across the whole cap, seen from above.",
          rim(),
          path("M30,34 L38,34 M28,48 L36,48 M30,62 L38,62 M58,34 L66,34 "
               "M60,48 L68,48 M58,62 L66,62", width=HAIR))
    write(f"art_{c}_darker_centre", "Amanita parcivolvata",
          "A darker disc at the centre fading outwards.",
          rim(),
          path("M48,28 Q66,28 66,48 Q66,68 48,68 Q30,68 30,48 Q30,28 48,28 Z", fill=True))
    write(f"art_{c}_paler_margin", "Panaeolus papilionaceus",
          "Dark over most of the cap, with a pale band at the edge.",
          rim(),
          path("M48,22 Q73,22 73,48 Q73,74 48,74 Q23,74 23,48 Q23,22 48,22 Z", fill=True),
          path("M48,30 Q64,30 64,48 Q64,66 48,66 Q32,66 32,48 Q32,30 48,30 Z"))


def launcher():
    write("art_launcher_chanterelle",
          "Cantharellus lateritius",
          "The launcher mark: wavy funnel cap and blunt decurrent ridges.",
          path("M12,36 Q24,22 36,32 Q48,20 60,31 Q74,22 84,36 "
               "L64,60 Q56,72 54,88 L42,88 Q40,72 32,60 Z"),
          path("M24,42 Q31,62 38,84 M38,39 Q42,60 44,86 M54,39 Q52,60 52,86 "
               "M68,42 Q60,60 55,82", width=FINE),
          path("M28,52 Q31,57 34,52 M46,49 Q49,54 52,49 M58,54 Q61,58 64,54",
               width=HAIR))


def interface_icons():
    """
    The two marks the interface itself needs. Written here so they share the hand.

    Not prefixed art_, because they are not character states and must not appear in
    the generated map or the contact sheet.
    """
    def plain(name, *paths):
        with open(os.path.join(OUT, f"{name}.xml"), "w") as f:
            f.write(HEADER + "".join(paths) + FOOTER)

    # An outlined i, per the house rule that About is an i in the corner.
    plain("ic_about",
          path("M48,12 Q84,12 84,48 Q84,84 48,84 Q12,84 12,48 Q12,12 48,12 Z"),
          path("M48,30 L48,32", width=7),
          path("M48,42 L48,66", width=6))

    plain("ic_remove",
          path("M24,32 L72,32"),
          path("M38,32 L38,24 Q38,20 42,20 L54,20 Q58,20 58,24 L58,32"),
          path("M30,32 L34,76 Q34,80 38,80 L58,80 Q62,80 62,76 L66,32"),
          path("M42,42 L43,70 M54,42 L53,70", width=FINE))


def emit_kotlin():
    """
    The map the app draws from, plus what each drawing is of.

    Generated rather than hand-kept so a new drawing cannot be added without its
    provenance, and so the two can never drift apart.
    """
    rows = []
    for name in sorted(EXEMPLARS):
        if name.startswith("art_launcher"):
            continue
        body = name[len("art_"):]
        species, why = EXEMPLARS[name]
        # Longest character id wins, so gill_edge does not swallow gill_edge_even.
        rows.append((body, name, species, why))

    def split(body):
        for cid in sorted(CHARACTERS, key=len, reverse=True):
            if body.startswith(cid + "_"):
                return cid, body[len(cid) + 1:]
        raise SystemExit(f"cannot split {body}")

    lines = [
        "package com.wanderwildwood.kinokocho.ui",
        "",
        "import com.wanderwildwood.kinokocho.R",
        "",
        "/**",
        " * The drawing for a character state, and the mushroom it was drawn from.",
        " *",
        " * Generated by tools/make-art.py. Do not edit by hand.",
        " *",
        " * Naming the species is not the app identifying anything — it is saying what the",
        " * picture is of, the way a field guide captions a plate. A reader who wants to know",
        " * why decurrent looks like that gets an answer; the mushroom in their hand is never",
        " * named by this app.",
        " */",
        "data class Art(val drawable: Int, val species: String?, val note: String)",
        "",
        "object CharacterArt {",
        "",
        "    private val byState: Map<String, Art> = mapOf(",
    ]
    for body, name, species, why in rows:
        cid, vid = split(body)
        sp = "null" if species == "—" else f"\"{species}\""
        lines.append(f'        "{cid}/{vid}" to Art(R.drawable.{name}, {sp}, "{why}"),')
    lines += [
        "    )",
        "",
        "    /** The drawing for a state, or null where none has been drawn yet. */",
        "    fun of(characterId: String, valueId: String): Art? = byState[\"$characterId/$valueId\"]",
        "",
        "    /** True when every state of a character has a drawing, so a grid is safe. */",
        "    fun coversAll(characterId: String, valueIds: List<String>): Boolean =",
        "        valueIds.isNotEmpty() && valueIds.all { byState.containsKey(\"$characterId/$it\") }",
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(KT), exist_ok=True)
    with open(KT, "w") as f:
        f.write("\n".join(lines))


CHARACTERS = [
    "fruitbody_type", "gill_attachment", "stipe_base", "cap_shape", "ring",
    "stipe_presence", "gill_spacing", "growth_habit", "cap_margin", "veil_remnants",
    "gill_edge", "stipe_flesh", "gill_extras", "cap_colour_pattern",
]

if __name__ == "__main__":
    fruitbody_type()
    gill_attachment()
    stipe_base()
    cap_shape()
    ring()
    stipe_presence()
    gill_spacing()
    growth_habit()
    cap_margin()
    veil_remnants()
    gill_edge()
    stipe_flesh()
    gill_extras()
    cap_colour_pattern()
    launcher()
    interface_icons()
    emit_kotlin()
    n = len([f for f in os.listdir(OUT) if f.startswith("art_")])
    species = sorted({s for s, _ in EXEMPLARS.values() if s != "—"})
    print(f"{n} drawings, from {len(species)} species")
    for s in species:
        print(f"  {s}")
