#!/usr/bin/env python3
"""
Draws the character states as line art, from real mushrooms.

On a panel with no colour, a picture of a gill attachment is not decoration — it is
the question. A reader in a wood can match a drawing against what is in their hand
faster than they can read "adnexed" and wonder whether that was the narrow one.

**Every drawing is of a named species that actually shows the character**, recorded in
EXEMPLARS below and emitted as Kotlin so the app can say what it drew. A generic
cartoon of "decurrent" teaches nothing; *Cantharellus* running down its own stem
teaches it in one look. Where a species is the textbook illustration of a character —
*Tricholoma* for a notched gill, *Amanita* for a sac volva — that is the one drawn.

What line art can carry honestly is silhouette, proportion and topology. That happens
to be exactly what these characters are: whether the gill reaches the stem, whether
the bulb has a rim, whether the tubes lift away from the cap. Colour and texture are
not attempted, because the panel has neither and the schema asks about them separately.

    python3 tools/make-art.py

Output is 96x96 vector drawables in app/src/main/res/drawable/, named
art_<character>_<value>.xml, stroke only. Drawn at about 56dp, so nothing finer than
a 3-unit gap survives — that is the constraint every drawing is built to.
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "app", "src", "main", "res", "drawable")
KT = os.path.join(HERE, "..", "app", "src", "main", "kotlin", "com",
                  "wanderwildwood", "kinokocho", "ui", "CharacterArt.kt")

# Lighter than the first pass. These started at 4.0/2.5/1.8 on the theory that an
# e-ink panel needs weight, and the drawings came out heavy and blunt — the owner compared
# them to a hand-drawn reference and the difference was line weight more than anything
# else. A pen drawing is thin and confident; thick strokes also close up small shapes,
# which is what wrecked the launcher icon. Legibility at 64px comes from clear shapes,
# not from fat lines.
STROKE = 2.8          # the silhouette
FINE = 1.9            # gills, tubes, cross-veins: things meant to read as many
HAIR = 1.3            # texture that must not compete with the silhouette
GROUND = 86.0

# The species each drawing is taken from, and what it is doing there. Written down
# because "based on a real mushroom" is a claim that has to be checkable, and because
# a reader who wants to know why the picture looks like that deserves an answer.
EXEMPLARS = {}


def drawn_from(name, species, why):
    EXEMPLARS[name] = (species, why)
    return name


# No android:tint here: the app themes with MMD, which does not carry
# ?attr/colorOnSurface, and aapt fails on every drawable if it is set. The Icon
# composable tints these at the call site instead, which is where the theme is.
HEADER = """<!-- Generated by tools/make-art.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="96dp"
    android:height="96dp"
    android:viewportWidth="96"
    android:viewportHeight="96">
"""
FOOTER = "</vector>\n"


def path(d, width=STROKE, fill=False, cap="round"):
    return (
        '    <path\n'
        f'        android:pathData="{d}"\n'
        f'        android:strokeColor="{"#00000000" if fill else "#FF000000"}"\n'
        f'        android:strokeWidth="{0 if fill else width}"\n'
        f'        android:fillColor="{"#FF000000" if fill else "#00000000"}"\n'
        f'        android:strokeLineCap="{cap}"\n'
        '        android:strokeLineJoin="round" />\n'
    )


def write(name, species, why, *paths):
    os.makedirs(OUT, exist_ok=True)
    assert re.fullmatch(r"[a-z0-9_]+", name), name
    drawn_from(name, species, why)
    with open(os.path.join(OUT, f"{name}.xml"), "w") as f:
        f.write(HEADER + "".join(paths) + FOOTER)


# ---------------------------------------------------------------------------
# Anatomy shared between drawings, so a stem is the same stem everywhere.

def ground(x1=10, x2=86, y=GROUND):
    return path(f"M{x1},{y} L{x2},{y}", width=FINE)


def stem_sides(x=48, top=48, bottom=GROUND, half=6):
    return f"M{x - half},{top} L{x - half},{bottom} M{x + half},{top} L{x + half},{bottom}"


def capped_cap(cx=48, half=34, base=46, rise=24, flesh=5):
    """
    A cap in section, with thickness.

    Cap flesh is not a line: gills hang from a wedge of tissue, and drawing it as one
    line is what makes amateur diagrams look wrong. The lower curve is where the gills
    attach, the upper is the surface.
    """
    return (
        f"M{cx - half},{base} "
        f"Q{cx - half},{base - rise} {cx},{base - rise} "
        f"Q{cx + half},{base - rise} {cx + half},{base} "
        f"Q{cx + half - 4},{base - flesh} {cx + half - 10},{base - flesh + 1} "
        f"L{cx - half + 10},{base - flesh + 1} "
        f"Q{cx - half + 4},{base - flesh} {cx - half},{base} Z"
    )


def tilted_cap(cx=48, cy=52, rx=34, ry=13, rise=22):
    """
    A cap seen from below and in front, so the underside is a surface and not an edge.

    Which of gills, tubes, pores, teeth or ridges a mushroom has is decided by looking
    underneath. Drawn in profile the answer is a few pixels of texture on a line; tilted,
    it is most of the picture. Field guides tilt for exactly this reason.
    """
    return path(
        f"M{cx - rx},{cy} "
        f"Q{cx - rx},{cy - rise} {cx},{cy - rise} "
        f"Q{cx + rx},{cy - rise} {cx + rx},{cy} "
        f"Q{cx + rx},{cy + ry} {cx},{cy + ry} "
        f"Q{cx - rx},{cy + ry} {cx - rx},{cy} Z"
    )


def underside_rim(cx=48, cy=52, rx=34, ry=13):
    """The ellipse where the cap edge meets the underside — the near edge only."""
    return path(
        f"M{cx - rx},{cy} Q{cx - rx},{cy + ry} {cx},{cy + ry} Q{cx + rx},{cy + ry} {cx + rx},{cy}",
        width=FINE,
    )


def radiating(cx=48, cy=52, rx=34, ry=13, n=13, inner=0.18, width=FINE):
    """
    Gills or ridges on a tilted underside: lines from the centre out to the rim.

    Foreshortened by the same ellipse as the rim, so they sit on the surface rather
    than floating over it.
    """
    import math
    d = []
    for i in range(n):
        # Only the front half is visible; the back is hidden by the cap.
        t = math.pi * (i / (n - 1))
        x = cx + rx * math.cos(t) * -1
        y = cy + ry * math.sin(t)
        xi = cx + (x - cx) * inner
        yi = cy + (y - cy) * inner
        d.append(f"M{xi:.1f},{yi:.1f} L{x:.1f},{y:.1f}")
    return path(" ".join(d), width=width)


def pore_field(cx=48, cy=54, rx=30, ry=10, rows=3, per=7, r=2.6, fine=False):
    """Round tube mouths on a tilted underside — a bolete's, drawn big enough to count."""
    import math
    d = []
    for j in range(rows):
        fy = (j + 1) / (rows + 0.6)
        for i in range(per):
            ft = (i + 0.5) / per
            x = cx - rx + 2 * rx * ft
            span = math.sqrt(max(0.0, 1 - ((x - cx) / rx) ** 2))
            y = cy + ry * fy * span
            rr = r * (0.75 + 0.25 * span)
            d.append(
                f"M{x - rr:.1f},{y:.1f} "
                f"Q{x - rr:.1f},{y - rr:.1f} {x:.1f},{y - rr:.1f} "
                f"Q{x + rr:.1f},{y - rr:.1f} {x + rr:.1f},{y:.1f} "
                f"Q{x + rr:.1f},{y + rr:.1f} {x:.1f},{y + rr:.1f} "
                f"Q{x - rr:.1f},{y + rr:.1f} {x - rr:.1f},{y:.1f} Z"
            )
    return path(" ".join(d), width=HAIR if fine else FINE)


def gill_blades(cx=48, half=34, base=45, depth=10, n=8, inner=12, taper=True):
    """
    Gills seen edge-on under a cap. They are deepest at mid-radius and shallow at the
    margin, which is what makes a gilled underside read as gills and not as a comb.
    """
    d = []
    step = (half - inner) / max(n - 1, 1)
    for i in range(n):
        off = inner + i * step
        frac = 1.0 - (off - inner) / max(half - inner, 1)
        dep = depth * (0.45 + 0.55 * frac) if taper else depth
        for sign in (-1, 1):
            x = cx + sign * off
            d.append(f"M{x:.1f},{base} L{x:.1f},{base + dep:.1f}")
    return path(" ".join(d), width=FINE)


# ---------------------------------------------------------------------------
# fruitbody_type — MycoKey's top-level split. Asked first, always.

def fruitbody_type():
    c = "fruitbody_type"

    # The first four are all decided by one look underneath, so all four are tilted to
    # put that surface where the eye lands. They differ only in what is on it.

    write(f"art_{c}_gilled_stemmed",
          "Agaricus campestris",
          "Underneath: blades radiating from the stem, thin and sharp-edged.",
          tilted_cap(),
          radiating(n=15),
          underside_rim(),
          path("M42,60 L42,86 M54,60 L54,86"),
          ground())

    # The tube layer is a mat of its own thickness, and the stem of a bolete is fat —
    # both are how you tell it from a gilled mushroom before you even look closely.
    write(f"art_{c}_bolete",
          "Boletus edulis",
          "Underneath: round tube mouths in a thick soft layer; the stem is stout.",
          path("M14,42 Q14,20 48,20 Q82,20 82,42 Q82,47 76,48 L20,48 Q14,47 14,42 Z"),
          path("M20,48 Q48,54 76,48 Q76,58 48,62 Q20,58 20,48 Z"),
          path("M27,52 Q27,49 30,49 Q33,49 33,52 Q33,55 30,55 Q27,55 27,52 Z "
               "M37,54 Q37,51 40,51 Q43,51 43,54 Q43,57 40,57 Q37,57 37,54 Z "
               "M47,55 Q47,52 50,52 Q53,52 53,55 Q53,58 50,58 Q47,58 47,55 Z "
               "M57,54 Q57,51 60,51 Q63,51 63,54 Q63,57 60,57 Q57,57 57,54 Z "
               "M66,51 Q66,48 69,48 Q72,48 72,51 Q72,54 69,54 Q66,54 66,51 Z",
               width=HAIR),
          path("M36,62 Q30,72 32,86 L64,86 Q66,72 60,62"),
          path("M35,70 Q48,74 62,70 M33,78 Q48,82 63,78", width=HAIR),
          ground())

    write(f"art_{c}_polypore",
          "Trametes versicolor",
          "Underneath: pores far finer than a bolete's, on a tough bracket with no stem.",
          path("M14,10 L14,86"),
          path("M14,36 Q44,26 80,42 Q80,52 76,54 Q44,46 14,54 Z"),
          path("M20,40 Q46,33 72,45 M24,45 Q48,39 76,50", width=HAIR),
          path("M20,54 Q46,48 74,58 Q46,58 20,60 Z"),
          pore_field(cx=46, cy=55, rx=24, ry=4, rows=2, per=9, r=1.5, fine=True))

    write(f"art_{c}_toothed",
          "Hydnum repandum",
          "Underneath: soft spines hanging down, not blades and not pores.",
          tilted_cap(rx=32, ry=11, rise=18),
          path("M18,54 L19,66 M24,57 L25,70 M30,59 L31,73 M36,61 L37,75 M42,62 L43,76 "
               "M48,62 L49,77 M54,62 L55,76 M60,61 L61,74 M66,59 L67,71 M72,56 L73,67 "
               "M78,53 L79,63", width=FINE),
          path("M42,62 Q41,74 42,86 M56,62 Q57,74 56,86"),
          ground())

    write(f"art_{c}_chanterelle_like",
          "Cantharellus lateritius",
          "Underneath: blunt forking ridges, thick and rounded where a gill is thin.",
          path("M12,32 Q22,20 32,28 Q42,18 50,26 Q60,17 70,27 Q82,20 86,34 "
               "Q76,44 66,50 L58,72 Q54,82 52,88 L44,88 Q42,78 38,70 L30,48 "
               "Q18,42 12,32 Z"),
          path("M24,36 Q30,50 34,62 M36,34 Q40,50 42,66 M50,32 Q50,50 49,68 "
               "M63,34 Q58,50 55,64 M74,36 Q66,46 62,54", width=STROKE),
          path("M28,44 Q31,48 34,44 M44,42 Q47,46 50,42 M55,46 Q58,50 61,46",
               width=FINE),
          ground(30, 66))

    write(f"art_{c}_coral_club",
          "Ramaria stricta",
          "Repeatedly forking upright branches from a common base, no cap anywhere.",
          path("M48,86 L48,60"),
          path("M48,60 Q40,50 34,38 M48,60 Q56,50 62,38 M48,62 Q46,48 44,34 "
               "M48,62 Q52,48 54,34"),
          path("M34,38 L28,24 M34,38 L36,22 M62,38 L60,22 M62,38 L68,24 "
               "M44,34 L40,20 M44,34 L46,18 M54,34 L52,18 M56,34 L60,20", width=FINE),
          ground(24, 72))

    # Lycoperdon: the sterile base is what separates a puffball from a ball of anything
    # else, and the apical pore is where the spores actually leave.
    write(f"art_{c}_gasteroid",
          "Lycoperdon perlatum",
          "Spores formed inside; sterile base tapering to the ground, pore at the top.",
          path("M30,50 Q30,28 48,28 Q66,28 66,50 Q66,62 62,70 "
               "Q60,80 54,86 L42,86 Q36,80 34,70 Q30,62 30,50 Z"),
          path("M44,30 Q48,26 52,30", width=FINE),
          path("M37,42 L39,44 M46,38 L48,40 M56,42 L58,44 M40,54 L42,56 M54,54 L56,56",
               width=HAIR),
          ground())

    write(f"art_{c}_cup_disc",
          "Peziza badia",
          "An ascomycete cup, sessile, hymenium on the inner face.",
          path("M18,40 Q18,74 48,74 Q78,74 78,40"),
          path("M18,40 Q48,28 78,40 Q48,50 18,40 Z"),
          path("M30,46 Q48,54 66,46", width=HAIR),
          ground(14, 82))

    write(f"art_{c}_resupinate",
          "Stereum ostrea",
          "A crust lying flat on wood, edge lifting only slightly.",
          path("M12,74 L84,74"),
          path("M20,74 Q22,58 34,60 Q46,46 60,58 Q76,56 78,74"),
          path("M24,70 Q28,64 34,66 M44,60 Q50,56 56,62 M62,64 Q68,62 72,70", width=HAIR),
          path("M20,74 Q18,70 16,72 M78,74 Q80,70 82,72", width=FINE))

    write(f"art_{c}_jelly",
          "Tremella mesenterica",
          "Gelatinous folded lobes with no cap, stem, gills or pores anywhere.",
          path("M16,60 Q14,44 26,40 Q30,26 42,32 Q50,22 58,32 Q70,26 74,38 "
               "Q86,44 82,60 Q80,74 60,78 Q34,82 22,72 Q16,68 16,60 Z"),
          path("M24,50 Q32,42 36,52 Q40,62 48,54 Q54,48 58,58 Q64,66 72,56",
               width=FINE),
          path("M28,66 Q36,58 42,68 Q50,76 58,68 Q64,62 70,68", width=FINE),
          path("M10,84 L86,84", width=FINE))

    write(f"art_{c}_flask",
          "Hypoxylon fragiforme",
          "A hard cushion on wood, cut to show flask-shaped chambers with necks to the surface.",
          path("M10,78 L86,78", width=FINE),
          path("M20,78 Q18,48 34,42 Q50,36 64,44 Q78,52 76,78 Z"),
          path("M30,60 Q30,53 35,53 Q40,53 40,60 Q40,67 35,67 Q30,67 30,60 Z", width=FINE),
          path("M46,64 Q46,56 51,56 Q56,56 56,64 Q56,71 51,71 Q46,71 46,64 Z", width=FINE),
          path("M60,58 Q60,52 64,52 Q68,52 68,58 Q68,64 64,64 Q60,64 60,58 Z", width=FINE),
          path("M35,53 L34,45 M51,56 L53,44 M64,52 L67,46", width=HAIR),
          path("M33,44 L35,43 M52,43 L54,42 M66,45 L68,44", width=FINE))

    # A stalked ascomycete with a pitted head. Drawn with the pits as a net of ridges
    # rather than as dots, because ridges-around-pits is what separates a morel from a
    # false morel's brain-like folds, and it is the first thing to look at.
    write(f"art_{c}_morel_like",
          "Morchella americana",
          "A pitted head fused to the stem, the pits enclosed by ridges.",
          path("M30,52 Q28,18 48,14 Q68,18 66,52 Q60,60 48,60 Q36,60 30,52 Z"),
          path("M34,26 Q48,22 62,26 M31,38 Q48,34 65,38 M33,50 Q48,46 63,50", width=FINE),
          path("M40,17 Q40,34 39,50 M48,14 L48,58 M56,17 Q56,34 57,50", width=FINE),
          path("M38,60 Q34,72 36,84 M58,60 Q62,72 60,84"),
          ground(28, 68))

    write(f"art_{c}_other",
          "—",
          "Not a taxon: the honest exit when nothing above fits.",
          path("M48,26 Q66,26 66,42 Q66,54 48,58 L48,66"),
          path("M48,76 L48,78", width=6))


# ---------------------------------------------------------------------------
# gill_attachment — one frame, one thing moving. iNaturalist field 917 verbatim.

def gill_attachment():
    """
    The junction, and almost nothing else.

    Drawn twice before and wrong both times. The first attempt was a whole mushroom and
    all six states came out identical. The second zoomed a little and worked on a
    contact sheet at 150px — and still failed at 64, which is the size these are
    actually drawn at. Where a gill meets a stem is a few millimetres of a mushroom; at
    64px, on a whole mushroom, it is two pixels.

    So this is a quarter view: cap flesh along the top, the stem as a band down the
    right, one gill filling the middle. Nothing else is in the frame, because nothing
    else is the question. The state is now a third of the picture rather than a
    detail in it, and the six read apart at the size they are used.

    This is also what the literature does. The Beaty Museum's teaching set, the NWFG
    notes and the Wisconsin Mycological Society all illustrate this character as a
    vertical section cropped to the gill-to-stipe junction, for the same reason: at any
    wider framing the thing being named is too small to see. The wording each state is
    drawn to is theirs — adnexed *diminishes* before attaching narrowly, sinuate becomes
    *suddenly* narrower, decurrent runs down *below the level of* the gills.

    ⚠ The literature separates *sinuate* from *emarginate*; NWFG has an article titled
    "Is it adnexed, emarginate or sinuate?" because they are genuinely confusable. This
    schema collapses them into `notched`, on purpose: a field journal that asks a
    question three mycologists argue about will get noise back.
    """
    c = "gill_attachment"

    def frame():
        # Cap above, stem to the right. The stem runs off the bottom edge: this is a
        # corner of a mushroom, not a small mushroom.
        return (
            path("M0,26 Q30,6 62,20 L62,30 Q30,18 0,36 Z", width=0, fill=True),
            path("M62,20 L62,96 M96,26 L96,96", width=STROKE),
        )

    write(f"art_{c}_free",
          "Agaricus campestris",
          "The gill stops short of the stem, leaving a clear gap all the way round it.",
          *frame(),
          path("M8,34 L46,28 L46,74 L8,66 Z", fill=True),
          # The gap is the whole character, so it is measured out with an arrow.
          path("M50,50 L58,50", width=FINE),
          path("M55,46 L59,50 L55,54", width=FINE))

    write(f"art_{c}_adnexed",
          "Mycena galericulata",
          "The gill reaches the stem, but touches over only the top of its depth.",
          *frame(),
          path("M8,34 L62,26 L62,40 L46,72 L8,66 Z", fill=True))

    write(f"art_{c}_adnate",
          "Gymnopus dryophilus",
          "The gill meets the stem squarely, over its whole depth.",
          *frame(),
          path("M8,34 L62,26 L62,76 L8,66 Z", fill=True))

    write(f"art_{c}_notched",
          "Tricholoma sejunctum",
          "The gill runs in deep, then is cut away sharply just before the stem.",
          *frame(),
          path("M8,34 L62,26 L62,38 L48,52 L48,84 L8,72 Z", fill=True))

    write(f"art_{c}_decurrent",
          "Cantharellus lateritius",
          "The gill does not stop at the stem — it turns and runs down the outside.",
          *frame(),
          path("M8,34 L62,26 L62,96 L44,96 L44,60 L8,66 Z", fill=True))

    write(f"art_{c}_no_stem",
          "Pleurotus ostreatus",
          "Attached to the wood at one side, so there is no stem for a gill to meet.",
          path("M0,26 Q34,6 74,22 L74,32 Q34,20 0,36 Z", width=0, fill=True),
          # The wood, not a stem.
          path("M88,4 L88,92", width=STROKE),
          path("M74,22 L88,26 L88,44 L74,40 Z", fill=True),
          path("M10,38 L10,64 M22,36 L22,68 M34,34 L34,72 M46,31 L46,74 M58,28 L58,74 "
               "M70,26 L70,70", width=STROKE))


# ---------------------------------------------------------------------------
# stipe_base — where the volva lives. These carry more weight than any other set.

def stipe_base():
    c = "stipe_base"
    top = path("M36,12 L36,40 M60,12 L60,40")

    write(f"art_{c}_equal",
          "Agaricus campestris",
          "The same width all the way down, ending flat in the soil.",
          top, path("M36,40 L36,80 M60,40 L60,80"), ground(22, 74, 80))

    write(f"art_{c}_bulbous",
          "Cortinarius alboviolaceus",
          "A stem that swells smoothly into a bulb, with no rim where it widens.",
          top,
          path("M36,40 Q34,58 28,66 Q28,78 48,79 Q68,78 68,66 Q62,58 60,40"),
          ground(18, 78, 80))

    # Amanita citrina: abruptly bulbous with a distinct gutter. The rim is the whole
    # character, so it is drawn as a hard shoulder rather than a curve.
    write(f"art_{c}_marginate",
          "Amanita citrina",
          "A bulb with a distinct rim and gutter where the stem meets it.",
          top,
          path("M36,40 L36,58 L26,62 L24,72 Q24,80 48,81 Q72,80 72,72 L70,62 L60,58 L60,40"),
          path("M24,66 Q48,71 72,66", width=FINE),
          ground(16, 80, 82))

    # The one drawing in the app that most needs to be right. A membranous sac with a
    # free upper limb, the stem rising cleanly out of it.
    write(f"art_{c}_sac_volva",
          "Amanita bisporigera",
          "A membranous bag with a free rim; the stem stands inside it, not fused to it.",
          top,
          path("M36,40 L36,66 M60,40 L60,66"),
          path("M28,56 Q22,70 24,79 Q30,86 48,86 Q66,86 72,79 Q74,70 68,56"),
          path("M28,56 Q32,63 36,66 M68,56 Q64,63 60,66"),
          path("M30,60 Q34,64 36,64 M66,60 Q62,64 60,64", width=HAIR),
          ground(14, 82, 88))

    write(f"art_{c}_volva_rings",
          "Amanita muscaria",
          "No bag — the volva left concentric rings of scales around a bulb.",
          top,
          path("M36,40 Q34,56 30,62 Q28,76 48,82 Q68,76 66,62 Q62,56 60,40"),
          path("M29,66 Q48,73 67,66 M30,72 Q48,79 66,72 M32,60 Q48,66 64,60", width=FINE),
          ground(18, 78, 86))

    write(f"art_{c}_rooting",
          "Hymenopellis radicata",
          "A pseudorhiza: the stem carries on below the soil as a long tapering root.",
          top,
          path("M36,40 L38,60 Q44,74 46,94 M60,40 L58,60 Q52,74 50,94"),
          path("M12,60 L84,60", width=FINE),
          path("M20,66 L28,66 M52,68 L62,68 M70,66 L78,66", width=HAIR))

    write(f"art_{c}_tapering",
          "Entoloma abortivum",
          "Narrowing steadily downwards, without ever swelling.",
          top, path("M36,40 L43,80 M60,40 L53,80"), ground(22, 74, 80))

    write(f"art_{c}_rhizomorphs",
          "Armillaria mellea",
          "Cords of mycelium leaving the base and running off through the substrate.",
          top,
          path("M36,40 L36,72 M60,40 L60,72"),
          path("M36,72 Q24,76 12,74 M38,74 Q28,84 16,86 M60,72 Q72,76 84,74 "
               "M58,74 Q68,84 80,86 M48,74 L48,86", width=FINE),
          ground(10, 86, 72))

    write(f"art_{c}_buried",
          "—",
          "Not a mushroom: the base was left in the ground, which is the commonest miss.",
          top,
          path("M36,40 L36,60 M60,40 L60,60"),
          path("M10,60 L86,60"),
          path("M18,68 L26,68 M34,68 L42,68 M50,68 L58,68 M66,68 L74,68 "
               "M22,76 L30,76 M38,76 L46,76 M54,76 L62,76 M26,84 L34,84 M50,84 L58,84",
               width=HAIR))


# ---------------------------------------------------------------------------
# cap_shape — the standard series, each on a species that holds that shape.

def cap_shape():
    c = "cap_shape"
    st = path("M44,64 L44,86 M52,64 L52,86")

    write(f"art_{c}_egg", "Coprinus comatus",
          "Taller than wide, sides near-parallel, before any expansion.",
          path("M32,68 Q30,22 48,20 Q66,22 64,68"),
          path("M44,68 L44,86 M52,68 L52,86"), ground())

    write(f"art_{c}_conical", "Hygrocybe conica",
          "Straight sides meeting at a point; never flattening with age.",
          path("M22,66 L48,18 L74,66 Q48,72 22,66 Z"), st, ground())

    write(f"art_{c}_bell", "Panaeolus papilionaceus",
          "Sides curve out and hang down: a bell, not a cone.",
          path("M24,66 Q24,24 48,24 Q72,24 72,66 Q48,72 24,66 Z"), st, ground())

    write(f"art_{c}_convex", "Agaricus campestris",
          "An even dome, the margin still turned down.",
          path("M16,58 Q16,30 48,30 Q80,30 80,58 Q48,66 16,58 Z"), st, ground())

    write(f"art_{c}_flat", "Russula virescens",
          "Expanded flat, the margin level with the centre.",
          path("M14,52 Q48,42 82,52 Q48,62 14,52 Z"), st, ground())

    # The three dished shapes are told apart by how the centre goes down, so each is
    # drawn to the glossary wording: depressed is merely lower, umbilicate is a sudden
    # small hole, funnel is deep enough to be a funnel. Drawn any softer they are one
    # picture three times at the size these are used.
    write(f"art_{c}_depressed", "Lactarius deliciosus",
          "Broad and saucer-like: the middle is lower, and no more than that.",
          path("M12,46 Q26,38 40,50 Q48,55 56,50 Q70,38 84,46 Q48,60 12,46 Z"),
          st, ground())

    write(f"art_{c}_funnel", "Clitocybe gibba",
          "The whole cap slopes down into the stem — a funnel, not a dish.",
          path("M10,28 L42,62 L54,62 L86,28 Q84,40 58,72 L38,72 Q12,40 10,28 Z"),
          path("M42,68 L42,86 M54,68 L54,86"), ground())

    write(f"art_{c}_umbonate", "Amanita parcivolvata",
          "A broad cap with a distinct raised boss at the centre.",
          path("M14,56 Q28,44 40,42 Q44,28 48,26 Q52,28 56,42 Q68,44 82,56 "
               "Q48,64 14,56 Z"), st, ground())

    write(f"art_{c}_umbilicate", "Arrhenia epichysium",
          "An otherwise flat cap with one sudden narrow pit, like a navel.",
          path("M12,44 Q28,38 44,42 L45,62 L51,62 L52,42 Q68,38 84,44 Q48,56 12,44 Z"),
          st, ground())


# ---------------------------------------------------------------------------

def ring():
    c = "ring"
    cap = path("M14,32 Q48,10 82,32 Q80,37 74,37 L22,37 Q14,37 14,32 Z")
    st = "M42,37 L42,86 M54,37 L54,86"

    write(f"art_{c}_absent", "Russula virescens",
          "No veil, so no ring is ever left behind.",
          cap, path(st))

    write(f"art_{c}_skirt", "Amanita bisporigera",
          "A membranous veil torn free at the margin and left hanging as a skirt.",
          cap, path(st),
          path("M42,52 Q28,54 24,66 Q34,72 48,70 Q62,72 72,66 Q68,54 54,52"),
          path("M32,62 Q40,66 48,66 Q56,66 64,62", width=HAIR))

    # Drawn at FINE and as a continuous band, not hairline ticks: at 64px the hairline
    # version was indistinguishable from no ring at all, and a cortina remnant against
    # a bare stem is the whole of the Cortinarius question.
    write(f"art_{c}_zone", "Cortinarius armillatus",
          "A cortina leaves no membrane, only a fibrous band where it broke.",
          cap, path(st),
          path("M30,52 L66,52 M30,62 L66,62", width=FINE),
          path("M34,52 L32,62 M40,52 L38,62 M46,52 L44,62 M52,52 L50,62 "
               "M58,52 L56,62 M64,52 L62,62", width=FINE))

    write(f"art_{c}_movable", "Amanita jacksonii",
          "A free collar that slides on the stem rather than gripping it.",
          cap, path(st),
          path("M30,58 Q48,50 66,58 Q48,66 30,58 Z"),
          path("M26,52 L20,47 M70,52 L76,47", width=FINE),
          path("M24,58 L18,58 M72,58 L78,58", width=HAIR))

    write(f"art_{c}_cannot_tell", "—",
          "Not a state of the mushroom: the specimen is too old or too damaged to say.",
          cap, path(st),
          path("M40,54 L34,56 M56,55 L62,58", width=HAIR),
          path("M48,74 Q60,74 60,65 Q60,59 48,59"),
          path("M48,84 L48,86", width=6))


def stipe_presence():
    c = "stipe_presence"

    write(f"art_{c}_central", "Agaricus campestris",
          "The stem meets the cap at its centre.",
          path(capped_cap(base=48, rise=22)), gill_blades(base=47, depth=8),
          path("M42,47 L42,86 M54,47 L54,86"), ground())

    write(f"art_{c}_off_centre", "Pluteus petasatus",
          "The stem meets the cap away from the centre, but not at the edge.",
          path(capped_cap(base=48, rise=22)), gill_blades(base=47, depth=8),
          path("M26,47 L26,86 M38,47 L38,86"), ground())

    # The stem is the whole difference from absent_attached, so it is drawn as a real
    # stubby stem standing clear of the wood, not two short marks. At 64px the marks
    # vanished and the two states were one picture.
    write(f"art_{c}_lateral", "Panellus stipticus",
          "A short stem at the very edge, holding the cap off the wood.",
          path("M88,10 L88,86", width=FINE),
          path("M66,34 Q40,20 12,36 Q10,42 16,44 Q42,44 66,44 Z"),
          path("M18,44 L20,54 M26,44 L28,56 M34,44 L36,56 M42,44 L44,55 "
               "M50,44 L52,53", width=HAIR),
          path("M66,32 L88,28 L88,50 L66,46 Z", fill=True))

    write(f"art_{c}_absent_attached", "Pleurotus ostreatus",
          "Joined straight to the wood with no stem at all.",
          path("M86,12 L86,84", width=FINE),
          path("M86,36 Q54,18 12,34 Q10,41 16,43 Q54,43 86,45 Z"),
          path("M18,42 L21,56 M27,42 L30,59 M36,43 L39,61 M45,43 L48,61 "
               "M54,43 L57,59 M63,43 L65,56", width=HAIR))

    write(f"art_{c}_absent_sitting", "Lycoperdon perlatum",
          "Sitting on the substrate, attached only by cords.",
          path("M24,56 Q24,32 48,32 Q72,32 72,56 Q72,72 48,76 Q24,72 24,56 Z"),
          path("M40,60 Q34,72 30,78 M56,60 Q62,72 66,78", width=HAIR),
          ground(14, 82, 78))


def gill_spacing():
    c = "gill_spacing"
    cap = path("M10,34 Q48,14 86,34 Q84,39 78,39 L18,39 Q10,39 10,34 Z")
    for name, n, species, why in (
        ("crowded", 17, "Marasmius oreades",
         "So many that the eye cannot separate them at the margin."),
        ("close", 10, "Agaricus campestris", "Regularly spaced, distinct, not touching."),
        ("distant", 5, "Omphalotus illudens",
         "Few and well apart, with cap flesh visible between."),
    ):
        d = []
        for i in range(n):
            x = 13 + i * (70 / (n - 1))
            frac = 1 - abs(x - 48) / 40
            d.append(f"M{x:.1f},39 L{x:.1f},{39 + 12 + 14 * frac:.1f}")
        write(f"art_{c}_{name}", species, why, cap, path(" ".join(d), width=FINE))


def growth_habit():
    c = "growth_habit"

    def little(x, y, half=12, rise=9, stem_len=17):
        return (f"M{x - half},{y} Q{x - half},{y - rise} {x},{y - rise} "
                f"Q{x + half},{y - rise} {x + half},{y} Z "
                f"M{x - 3},{y} L{x - 3},{y + stem_len} M{x + 3},{y} L{x + 3},{y + stem_len}")

    write(f"art_{c}_single", "Amanita bisporigera",
          "One fruitbody, alone.",
          path(little(48, 60)), ground(22, 74))

    write(f"art_{c}_few", "Boletus edulis",
          "A few, each with its own base, not touching.",
          path(little(28, 62) + " " + little(66, 58)), ground())

    write(f"art_{c}_troop", "Marasmius oreades",
          "Many scattered across the ground, unconnected.",
          path(little(18, 50, 8, 6, 12) + " " + little(44, 62, 11, 8, 16) + " " +
               little(72, 48, 8, 6, 12) + " " + little(58, 36, 7, 5, 10)),
          ground())

    write(f"art_{c}_caespitose", "Armillaria mellea",
          "Clustered, the bases crowded together but still separate.",
          path(little(32, 52, 11, 8, 22) + " " + little(60, 48, 11, 8, 26) + " " +
               little(46, 62, 11, 8, 16)),
          ground(22, 74))

    write(f"art_{c}_fused", "Omphalotus illudens",
          "Bases run together into one mass — you cannot pull one out alone.",
          path(little(32, 48, 11, 8, 0) + " " + little(60, 46, 11, 8, 0)),
          path("M30,48 Q36,62 40,80 M62,46 Q58,62 56,80 M44,52 L46,80 M52,52 L50,80"),
          path("M38,80 Q48,84 58,80"),
          ground(24, 72))

    write(f"art_{c}_ring", "Marasmius oreades",
          "A fairy ring: the arc of an outward-growing mycelium.",
          path("M18,64 Q48,50 78,64 Q48,78 18,64 Z", width=FINE),
          path("M24,58 L24,50 M40,54 L40,46 M56,54 L56,46 M72,58 L72,50 "
               "M32,72 L32,64 M64,72 L64,64", width=FINE))

    write(f"art_{c}_tiered", "Trametes versicolor",
          "Shelving in overlapping tiers up a trunk.",
          path("M16,12 L16,86"),
          path("M16,28 Q38,22 58,34 Q38,40 16,38 Z"),
          path("M16,48 Q42,42 66,54 Q42,60 16,58 Z"),
          path("M16,68 Q36,64 54,72 Q36,78 16,76 Z"))


def cap_margin():
    c = "cap_margin"
    body = path("M14,50 Q48,24 82,50")

    write(f"art_{c}_inrolled", "Paxillus involutus",
          "Rolled right under, so the edge points back at the stem.",
          body, path("M14,50 Q6,60 16,66 Q26,62 20,52 M82,50 Q90,60 80,66 Q70,62 76,52"))
    write(f"art_{c}_incurved", "Agaricus campestris",
          "Curved inwards but not rolled.",
          body, path("M14,50 Q12,62 24,65 M82,50 Q84,62 72,65"))
    write(f"art_{c}_straight", "Russula virescens",
          "Meeting the cap surface at a straight edge.",
          body, path("M14,50 L14,64 M82,50 L82,64"))
    write(f"art_{c}_uplifted", "Clitocybe gibba",
          "Turned up with age, exposing the gills from the side.",
          path("M14,42 Q34,60 48,42 Q62,60 82,42"),
          path("M44,44 L44,82 M52,44 L52,82"))
    write(f"art_{c}_wavy", "Cantharellus lateritius",
          "Irregularly lobed and waved rather than circular.",
          path("M12,52 Q22,40 32,52 Q42,64 52,52 Q62,40 72,52 Q78,58 84,52"),
          path("M44,58 L44,84 M52,58 L52,84"))
    write(f"art_{c}_striate", "Amanita parcivolvata",
          "Grooved at the edge, following the gills beneath.",
          body, path("M20,54 L18,64 M30,49 L29,61 M40,46 L40,59 M56,46 L56,59 "
                     "M66,49 L67,61 M76,54 L78,64", width=HAIR))
    write(f"art_{c}_translucent_striate", "Mycena galericulata",
          "Flesh thin enough that the gills show through as lines.",
          body,
          path("M18,54 L16,66 M28,49 L27,63 M38,46 L38,61 M48,44 L48,60 "
               "M58,46 L58,61 M68,49 L69,63 M78,54 L80,66", width=HAIR),
          path("M38,72 L58,72 M44,78 L52,78", width=HAIR))
    write(f"art_{c}_appendiculate", "Coprinus comatus",
          "Fragments of the veil left hanging from the edge.",
          body,
          path("M18,54 Q20,62 16,66 M30,50 Q32,60 28,65 M42,47 Q44,58 40,64 "
               "M54,47 Q56,58 52,64 M66,50 Q68,60 64,65 M78,55 Q80,63 76,67",
               width=HAIR))


def veil_remnants():
    c = "veil_remnants"
    body = path("M14,52 Q48,24 82,52 Q80,57 74,57 L22,57 Q14,57 14,52 Z")
    st = path("M44,57 L44,86 M52,57 L52,86")

    write(f"art_{c}_none", "Russula virescens",
          "Nothing on the cap: there was no universal veil to leave anything.",
          body, st)
    write(f"art_{c}_warts", "Amanita muscaria",
          "Loose warts of universal veil, easily rubbed or washed off.",
          body, st,
          path("M30,44 Q34,39 39,44 Q34,49 30,44 Z M44,34 Q49,29 54,34 Q49,39 44,34 Z "
               "M58,42 Q63,37 68,42 Q63,47 58,42 Z M22,50 Q26,46 30,50 Q26,54 22,50 Z "
               "M68,50 Q72,46 76,50 Q72,54 68,50 Z"))
    write(f"art_{c}_single_patch", "Amanita parcivolvata",
          "One large sheet of veil left sitting on the cap.",
          body, st,
          path("M34,34 Q48,25 64,36 Q58,49 42,47 Z"),
          path("M42,38 Q50,36 56,40", width=HAIR))
    write(f"art_{c}_fibrous_scales", "Pholiota squarrosa",
          "Recurved scales that are part of the cap skin, not loose patches.",
          body, st,
          path("M26,50 Q30,42 34,46 M38,44 Q42,35 46,40 M52,38 Q56,33 58,42 "
               "M62,42 Q67,36 70,46 M32,54 Q36,48 40,52 M56,52 Q60,46 64,53",
               width=HAIR))
    write(f"art_{c}_peeling_skin", "Pluteus petasatus",
          "A cuticle lifting and peeling back from the margin.",
          body, st,
          path("M14,52 Q26,42 36,50 Q30,60 18,60"),
          path("M20,54 Q26,50 32,53", width=HAIR))


def gill_edge():
    c = "gill_edge"

    def face():
        return path("M16,26 L16,64 M80,26 L80,64 M16,26 L80,26", width=FINE)

    write(f"art_{c}_even", "Agaricus campestris",
          "A clean straight edge, seen face-on.",
          face(), path("M16,64 L80,64"))
    write(f"art_{c}_serrate", "Lentinellus ursinus",
          "Regularly toothed, like a saw.",
          face(),
          path("M16,64 L22,57 L28,64 L34,57 L40,64 L46,57 L52,64 L58,57 "
               "L64,64 L70,57 L76,64 L80,60"))
    write(f"art_{c}_wavy", "Pleurotus ostreatus",
          "Undulating without discrete teeth.",
          face(), path("M16,62 Q26,52 36,62 Q46,72 56,62 Q66,52 76,62 Q79,64 80,63"))
    write(f"art_{c}_different_colour", "Mycena galericulata",
          "The edge is pigmented differently from the gill face.",
          face(), path("M16,60 L80,60 L80,68 L16,68 Z", fill=True))


def stipe_flesh():
    c = "stipe_flesh"

    def outer():
        return path("M32,10 L32,84 M64,10 L64,84 M32,84 Q48,88 64,84")

    write(f"art_{c}_solid", "Boletus edulis",
          "Filled right through with unbroken flesh.",
          outer(),
          path("M37,20 L59,42 M37,36 L59,58 M37,52 L59,74 M37,68 L53,84 M45,16 L59,30",
               width=HAIR))
    write(f"art_{c}_stuffed", "Agaricus campestris",
          "A softer pith down the middle, distinct from the wall.",
          outer(),
          path("M40,14 Q47,28 40,42 Q47,56 40,70 Q46,79 42,84 "
               "M56,14 Q49,28 56,42 Q49,56 56,70 Q50,79 54,84", width=FINE))
    write(f"art_{c}_hollow", "Marasmius oreades",
          "An open tube: the wall is all there is.",
          outer(), path("M40,12 L40,84 M56,12 L56,84"))
    write(f"art_{c}_chambered", "Coprinus comatus",
          "Cross-walls dividing the hollow into chambers.",
          outer(),
          path("M40,12 L40,84 M56,12 L56,84"),
          path("M40,30 Q48,34 56,30 M40,48 Q48,52 56,48 M40,66 Q48,70 56,66", width=FINE))


def gill_extras():
    c = "gill_extras"

    def cap():
        return path("M10,30 Q48,12 86,30 Q84,35 78,35 L18,35 Q10,35 10,30 Z")

    write(f"art_{c}_lamellulae", "Agaricus campestris",
          "Short gills starting at the margin, not reaching the stem.",
          cap(),
          path("M14,35 L14,68 M26,35 L26,68 M38,35 L38,68 M50,35 L50,68 "
               "M62,35 L62,68 M74,35 L74,68", width=FINE),
          path("M20,35 L20,52 M32,35 L32,52 M44,35 L44,52 M56,35 L56,52 "
               "M68,35 L68,52 M80,35 L80,52", width=HAIR))
    write(f"art_{c}_forked", "Russula virescens",
          "Gills dividing in two on their way to the margin.",
          cap(),
          path("M18,35 L18,50 Q18,58 13,68 M18,50 Q18,58 24,68 "
               "M40,35 L40,50 Q40,58 35,68 M40,50 Q40,58 46,68 "
               "M62,35 L62,50 Q62,58 57,68 M62,50 Q62,58 68,68 "
               "M80,35 L80,68 M30,35 L30,68 M52,35 L52,68", width=FINE))
    write(f"art_{c}_veined", "Cantharellus lateritius",
          "Cross-veins bridging between the ridges.",
          cap(),
          path("M16,35 L16,68 M30,35 L30,68 M44,35 L44,68 M58,35 L58,68 "
               "M72,35 L72,68", width=FINE),
          path("M16,46 Q23,52 30,46 Q37,52 44,46 Q51,52 58,46 Q65,52 72,46 "
               "M16,58 Q23,63 30,58 Q37,63 44,58 Q51,63 58,58", width=HAIR))


def cap_colour_pattern():
    c = "cap_colour_pattern"

    def rim():
        return path("M48,16 Q80,16 80,48 Q80,80 48,80 Q16,80 16,48 Q16,16 48,16 Z")

    write(f"art_{c}_uniform", "Russula virescens",
          "One tone across the whole cap, seen from above.",
          rim(),
          path("M30,34 L38,34 M28,48 L36,48 M30,62 L38,62 M58,34 L66,34 "
               "M60,48 L68,48 M58,62 L66,62", width=HAIR))
    write(f"art_{c}_darker_centre", "Amanita parcivolvata",
          "A darker disc at the centre fading outwards.",
          rim(),
          path("M48,28 Q66,28 66,48 Q66,68 48,68 Q30,68 30,48 Q30,28 48,28 Z", fill=True))
    write(f"art_{c}_paler_margin", "Panaeolus papilionaceus",
          "Dark over most of the cap, with a pale band at the edge.",
          rim(),
          path("M48,22 Q73,22 73,48 Q73,74 48,74 Q23,74 23,48 Q23,22 48,22 Z", fill=True),
          path("M48,30 Q64,30 64,48 Q64,66 48,66 Q32,66 32,48 Q32,30 48,30 Z"))


def substrate():
    """
    What it is growing on. Asked second every time, and the answer is usually visible
    without touching anything, so it earns pictures more than most.
    """
    c = "substrate"

    write(f"art_{c}_wood", "—", "A log, branch or stump.",
          path("M10,44 Q10,34 20,34 L76,34 Q86,34 86,44 L86,58 Q86,68 76,68 L20,68 "
               "Q10,68 10,58 Z"),
          path("M20,34 Q28,34 28,51 Q28,68 20,68", width=FINE),
          path("M20,51 Q24,45 24,51 Q24,57 20,58", width=HAIR),
          path("M40,38 L44,64 M56,36 L60,66", width=HAIR))

    write(f"art_{c}_soil", "—", "Bare ground, with nothing between it and the fungus.",
          path("M8,44 L88,44"),
          path("M16,54 L26,54 M34,52 L46,52 M54,54 L66,54 M72,52 L82,52 "
               "M20,64 L32,64 M40,62 L52,62 M60,64 L72,64 M28,74 L40,74 M52,74 L64,74",
               width=HAIR))

    write(f"art_{c}_litter", "—", "Fallen leaves and needles, not the soil beneath them.",
          path("M8,62 L88,62", width=FINE),
          path("M14,62 Q20,48 34,52 Q30,64 14,62 Z"),
          path("M32,58 Q42,44 56,50 Q50,62 32,58 Z"),
          path("M54,62 Q64,50 78,56 Q72,66 54,62 Z"),
          path("M22,56 L28,58 M42,52 L50,55 M64,58 L72,60", width=HAIR))

    write(f"art_{c}_grass", "—", "Lawn, pasture or verge.",
          path("M8,80 L88,80", width=FINE),
          path("M16,80 Q14,60 20,48 M26,80 Q28,62 24,52 M36,80 Q34,58 40,44 "
               "M46,80 Q48,60 44,50 M56,80 Q54,58 60,46 M66,80 Q68,62 64,52 "
               "M76,80 Q74,62 80,50"))

    write(f"art_{c}_moss", "—", "A moss cushion, on ground or on wood.",
          path("M10,72 Q10,58 22,58 Q26,46 40,52 Q52,42 62,54 Q78,52 80,66 "
               "Q88,70 84,78 L12,78 Q6,74 10,72 Z"),
          path("M22,58 L22,50 M34,52 L34,44 M46,50 L46,42 M58,52 L58,44 M70,56 L70,48",
               width=HAIR))

    write(f"art_{c}_dung", "—", "Droppings, usually of a grazing animal.",
          path("M8,76 L88,76", width=FINE),
          path("M22,76 Q20,60 34,58 Q42,50 54,58 Q70,58 70,76 Z"),
          path("M32,68 Q40,64 48,68 M50,62 Q56,60 60,64", width=HAIR))

    write(f"art_{c}_another_fungus", "—", "Growing out of another fungus.",
          path("M14,74 Q14,56 34,56 Q54,56 54,74 Z"),
          path("M8,74 L88,74", width=FINE),
          path("M44,54 Q44,42 56,42 Q68,42 68,54 Q60,58 56,58 Q48,58 44,54 Z"),
          path("M54,54 L54,70 M60,54 L60,70", width=FINE))

    write(f"art_{c}_living_plant", "—", "On a living plant, not on dead wood.",
          path("M48,84 L48,30"),
          path("M48,58 Q32,54 26,40 Q42,38 48,52 M48,46 Q64,42 70,28 Q54,26 48,40"),
          path("M48,34 Q40,26 44,16 Q52,22 48,32", width=FINE))

    write(f"art_{c}_animal", "—", "On an insect or other animal.",
          path("M8,74 L88,74", width=FINE),
          path("M26,62 Q20,56 26,50 Q32,46 40,50 L58,50 Q70,50 72,58 Q70,66 58,66 "
               "L40,66 Q30,68 26,62 Z"),
          path("M40,50 L40,66 M52,50 L52,66", width=FINE),
          path("M34,66 L30,74 M46,66 L44,74 M58,66 L60,74", width=HAIR),
          path("M26,50 L20,42 M30,48 L28,40", width=HAIR),
          path("M48,50 Q52,38 60,32 M56,50 Q62,40 70,36", width=FINE))

    write(f"art_{c}_burnt", "—", "A burnt site: charcoal, or ground after a fire.",
          path("M8,74 L88,74", width=FINE),
          path("M16,74 L24,54 L34,74 Z", fill=True),
          path("M38,74 L48,48 L58,74 Z", fill=True),
          path("M62,74 L70,58 L80,74 Z", fill=True),
          path("M28,44 Q32,38 30,32 M52,40 Q56,32 54,26 M72,48 Q76,42 74,36",
               width=HAIR))

    write(f"art_{c}_stone", "—", "Rock, wall or bare stone.",
          path("M14,76 L24,46 L44,36 L68,44 L82,68 L76,78 Z"),
          path("M24,46 L46,58 L68,44 M46,58 L44,78", width=HAIR),
          path("M8,80 L88,80", width=FINE))

    write(f"art_{c}_other", "—", "Something else entirely.",
          path("M48,26 Q66,26 66,42 Q66,54 48,58 L48,66"),
          path("M48,76 L48,78", width=6))


def latex():
    """
    Whether it bleeds. Drawn as a snapped stem rather than a flat cut face, because
    the first attempt read as a heraldic shield and because snapping is what a person
    actually does.
    """
    c = "latex"

    def snapped():
        # The cap stays on the upper half, so the picture reads as a mushroom broken
        # in two rather than as a bracket. Without it the frame is an abstract H.
        return (
            path("M14,26 Q48,6 82,26 Q80,31 74,31 L22,31 Q14,31 14,26 Z"),
            path("M34,31 L34,44 L62,44 L62,31"),
            path("M34,56 L34,86 M62,56 L62,86"),
            path("M34,56 L62,56", width=FINE),
        )

    write(f"art_{c}_none", "Russula virescens",
          "Snap it, and nothing comes out of the break.",
          *snapped())

    write(f"art_{c}_present", "Lactifluus volemus",
          "White drops stand on the break at once, and go on coming.",
          *snapped(),
          path("M40,46 Q36,52 40,55 Q45,55 45,50 Q45,48 43,44 Z", fill=True),
          path("M54,46 Q50,52 54,55 Q59,55 59,50 Q59,48 57,44 Z", fill=True),
          path("M47,48 Q44,53 47,56 Q51,56 51,52 Q51,50 49,47 Z", fill=True))

    write(f"art_{c}_watery", "Mycena galericulata",
          "A thin clear liquid rather than a milk: it wets the break and runs.",
          *snapped(),
          path("M40,46 Q36,52 40,55 Q45,55 45,50 Q45,48 43,44 Z", width=FINE),
          path("M55,47 Q52,52 55,55 Q59,55 59,51 Q59,49 57,46 Z", width=FINE))

    write(f"art_{c}_guttation", "—",
          "Beads standing on the outside of an uncut mushroom.",
          path(capped_cap(base=44, rise=20)),
          path("M42,44 L42,80 M54,44 L54,80"),
          path("M30,32 Q27,38 30,41 Q35,41 35,36 Q35,34 33,30 Z", fill=True),
          path("M60,30 Q57,36 60,39 Q65,39 65,34 Q65,32 63,28 Z", fill=True),
          path("M46,54 Q43,60 46,63 Q51,63 51,58 Q51,56 49,52 Z", fill=True),
          ground())


def bruising():
    """A cap seen from above, with the mark a thumb left on it."""
    c = "bruising"

    def cap_above():
        return path("M48,14 Q82,14 82,48 Q82,82 48,82 Q14,82 14,48 Q14,14 48,14 Z")

    write(f"art_{c}_no", "Russula virescens",
          "Pressed hard, and the colour does not move.",
          cap_above(),
          path("M38,40 Q38,30 48,30 Q58,30 58,40 Q58,54 48,58 Q38,54 38,40 Z",
               width=FINE),
          path("M30,66 L40,58 M66,66 L56,58", width=HAIR))

    write(f"art_{c}_yes", "Suillellus subvelutipes",
          "A dark stain spreads where the thumb was.",
          cap_above(),
          path("M38,40 Q38,30 48,30 Q58,30 58,40 Q58,54 48,58 Q38,54 38,40 Z",
               fill=True),
          path("M34,62 Q48,68 62,62", width=HAIR))


def associated_tree():
    c = "associated_tree"

    write(f"art_{c}_conifer", "—", "Pine, hemlock, spruce: needles and cones.",
          path("M48,84 L48,20"),
          path("M48,26 L30,40 M48,26 L66,40 M48,40 L26,56 M48,40 L70,56 "
               "M48,54 L22,72 M48,54 L74,72"))

    write(f"art_{c}_broadleaf", "—", "Oak, beech, poplar: a broad leaf.",
          path("M48,84 L48,52"),
          path("M48,52 Q22,48 20,28 Q44,24 48,44 Q52,24 76,28 Q74,48 48,52 Z"),
          path("M34,32 L44,42 M62,32 L52,42", width=HAIR))

    write(f"art_{c}_unknown", "—", "Not known, or nothing close enough to say.",
          path("M48,26 Q66,26 66,42 Q66,54 48,58 L48,66"),
          path("M48,76 L48,78", width=6))


def cap_surface():
    """
    A patch of cap, always the same patch, so only the texture moves. Drawn as a
    magnified swatch rather than a whole mushroom: at 56dp a texture on a full cap is
    three pixels of noise.
    """
    c = "cap_surface"

    def swatch():
        return path("M20,20 Q48,12 76,20 Q84,48 76,76 Q48,84 20,76 Q12,48 20,20 Z")

    write(f"art_{c}_smooth", "Russula virescens", "Even and unbroken.",
          swatch())
    write(f"art_{c}_viscid", "Suillus americanus", "Slimy or sticky, and it shines wet.",
          swatch(),
          path("M28,34 Q38,30 46,36 M52,44 Q62,40 70,46 M26,56 Q36,52 44,58 "
               "M50,66 Q60,62 68,68", width=FINE),
          path("M60,28 Q64,26 66,30", width=HAIR))
    write(f"art_{c}_dry", "Agaricus campestris", "Matt and dry to the finger.",
          swatch(),
          path("M32,40 L36,40 M46,36 L50,36 M60,42 L64,42 M36,56 L40,56 "
               "M52,58 L56,58 M44,68 L48,68", width=HAIR))
    write(f"art_{c}_silky", "Inocybe rimosa", "Fine parallel fibres, like brushed silk.",
          swatch(),
          path("M24,30 Q48,26 72,32 M22,42 Q48,38 74,44 M22,54 Q48,50 74,56 "
               "M24,66 Q48,62 72,68", width=HAIR))
    write(f"art_{c}_scaly", "Pholiota squarrosa", "Flat scales that are part of the skin.",
          swatch(),
          path("M28,34 L38,30 L40,40 Z M48,28 L58,26 L58,38 Z M62,38 L72,36 L70,46 Z "
               "M30,52 L40,48 L42,58 Z M50,50 L60,48 L60,58 Z M34,68 L44,64 L46,74 Z "
               "M56,66 L66,62 L66,72 Z"))
    write(f"art_{c}_warty", "Amanita muscaria", "Loose warts sitting on the surface.",
          swatch(),
          path("M30,34 Q35,29 40,34 Q35,39 30,34 Z M50,28 Q55,23 60,28 Q55,33 50,28 Z "
               "M62,44 Q67,39 72,44 Q67,49 62,44 Z M28,54 Q33,49 38,54 Q33,59 28,54 Z "
               "M48,52 Q53,47 58,52 Q53,57 48,52 Z M38,68 Q43,63 48,68 Q43,73 38,68 Z "
               "M58,66 Q63,61 68,66 Q63,71 58,66 Z"))
    write(f"art_{c}_velvety", "Xerocomellus chrysenteron",
          "Short dense pile, like the back of a leaf.",
          swatch(),
          path("M26,32 L26,26 M34,30 L34,24 M42,29 L42,23 M50,29 L50,23 M58,30 L58,24 "
               "M66,32 L66,26 M24,44 L24,38 M72,44 L72,38 M24,58 L24,52 M72,58 L72,52",
               width=HAIR),
          path("M32,44 L32,50 M44,42 L44,48 M56,44 L56,50 M38,58 L38,64 M52,58 L52,64",
               width=HAIR))
    write(f"art_{c}_hairy", "Trametes hirsuta", "Long distinct hairs, not a pile.",
          swatch(),
          path("M26,28 Q22,18 28,12 M38,24 Q34,14 40,8 M50,23 Q48,12 54,8 "
               "M62,26 Q60,16 68,12 M72,34 Q72,24 80,20", width=FINE))
    write(f"art_{c}_wrinkled", "Gyromitra caroliniana",
          "Folded into ridges and hollows, like a brain.",
          swatch(),
          path("M24,34 Q34,26 42,36 Q50,46 60,36 Q68,28 74,38 "
               "M22,52 Q32,44 40,54 Q48,64 58,54 Q66,46 74,56 "
               "M28,70 Q38,62 46,72 Q54,80 62,72", width=FINE))
    write(f"art_{c}_cracked", "Russula virescens",
          "Split into patches with the flesh showing between.",
          swatch(),
          path("M40,14 L38,40 L20,50 M38,40 L62,44 L76,26 M62,44 L58,80 "
               "M62,44 L82,58 M38,40 L30,76", width=FINE))
    write(f"art_{c}_striate", "Amanita parcivolvata",
          "Lined or grooved, usually following the gills beneath.",
          swatch(),
          path("M30,18 L26,78 M40,15 L38,82 M50,14 L50,83 M60,15 L62,82 M70,19 L74,76",
               width=FINE))
    # The character is not "there are specks on it" — dry has those too — it is that a
    # finger takes them off. So the drawing is the wipe: a clean streak through the
    # bloom, which is what the reader actually does to test it.
    write(f"art_{c}_powdery", "Cystoderma amianthinum",
          "A loose bloom that a finger wipes away, leaving a clean streak.",
          swatch(),
          path("M28,28 L29,28 M40,26 L41,26 M52,28 L53,28 M64,32 L65,32 "
               "M26,40 L27,40 M38,38 L39,38 M62,44 L63,44 "
               "M30,68 L31,68 M42,70 L43,70 M56,70 L57,70 M66,64 L67,64", width=4),
          path("M24,54 Q48,48 72,56", width=9, cap="butt"),
          path("M24,54 Q48,48 72,56", width=7, cap="butt", fill=False))
    # Bands, not lines: silky is fine parallel fibres and at 64px a thin-lined zoned cap
    # was the same picture. Alternate bands are filled so the eye reads tone, which is
    # what zonation is.
    write(f"art_{c}_zoned", "Trametes versicolor", "Concentric bands of alternating tone.",
          swatch(),
          path("M21,34 Q48,28 75,34 Q48,40 21,46 Z", fill=True),
          path("M20,56 Q48,50 76,56 Q48,62 20,68 Z", fill=True))


def stipe_surface():
    """A length of stem, magnified, with only the surface changing."""
    c = "stipe_surface"

    def band():
        return path("M32,12 L32,84 M64,12 L64,84")

    write(f"art_{c}_smooth", "Agaricus campestris", "Even, with nothing on it.",
          band())
    write(f"art_{c}_fibrous", "Pholiota squarrosa", "Streaked lengthways with fibres.",
          band(),
          path("M38,14 Q36,48 38,82 M45,13 Q44,48 45,83 M52,13 Q53,48 52,83 "
               "M58,14 Q60,48 58,82", width=HAIR))
    write(f"art_{c}_scaly", "Pholiota squarrosa", "Scales standing off the surface.",
          band(),
          path("M36,24 L46,22 L44,32 Z M50,20 L60,20 L58,30 Z M36,44 L46,42 L44,52 Z "
               "M50,48 L60,46 L58,56 Z M38,66 L48,64 L46,74 Z M52,70 L62,68 L60,78 Z"))
    write(f"art_{c}_reticulate", "Tylopilus felleus", "A raised net over the surface.",
          band(),
          path("M32,26 L64,26 M32,42 L64,42 M32,58 L64,58 M32,74 L64,74", width=HAIR),
          path("M40,12 L40,84 M48,12 L48,84 M56,12 L56,84", width=HAIR))
    write(f"art_{c}_punctate", "Suillellus subvelutipes", "Scattered granular dots.",
          band(),
          path("M38,22 L39,22 M50,20 L51,20 M58,26 L59,26 M40,36 L41,36 M52,34 L53,34 "
               "M60,42 L61,42 M38,50 L39,50 M50,48 L51,48 M58,58 L59,58 M42,64 L43,64 "
               "M54,68 L55,68 M38,76 L39,76", width=4))
    # Same test as the cap: powder is the stuff a finger takes off. Punctate dots are
    # part of the surface and stay, so the wipe is what separates the two pictures.
    write(f"art_{c}_powdery", "Cystoderma amianthinum",
          "A bloom that wipes off, leaving a clean streak.",
          band(),
          path("M37,20 L38,20 M45,26 L46,26 M53,22 L54,22 M59,30 L60,30 "
               "M36,38 L37,38 M46,42 L47,42 M58,38 L59,38 "
               "M38,70 L39,70 M50,74 L51,74 M58,68 L59,68", width=3),
          path("M33,54 Q48,50 63,56", width=10, cap="butt"),
          path("M33,54 Q48,50 63,56", width=8, cap="butt", fill=False))
    write(f"art_{c}_hairy", "Panellus stipticus", "Distinct hairs standing off it.",
          band(),
          path("M32,22 L24,18 M32,36 L23,33 M32,50 L24,47 M32,64 L23,61 "
               "M64,26 L73,22 M64,40 L72,37 M64,54 L73,51 M64,68 L72,65", width=HAIR))
    write(f"art_{c}_slimy", "Suillus americanus", "Sticky, and it shines.",
          band(),
          path("M38,20 Q46,16 54,22 M40,40 Q48,36 58,42 M38,60 Q46,56 56,62 "
               "M42,76 Q50,72 58,78", width=FINE),
          path("M54,30 Q58,28 60,32", width=HAIR))
    # A groove changes the silhouette and a fibre does not — that is the difference, and
    # drawing both as vertical lines made them one picture at 64px. So the edges are
    # fluted here and the channels are heavy.
    write(f"art_{c}_grooved", "Cantharellus lateritius", "Ridged and furrowed lengthways.",
          path("M32,12 Q28,30 32,48 Q28,66 32,84 M64,12 Q68,30 64,48 Q68,66 64,84"),
          path("M42,12 L42,84 M54,12 L54,84", width=STROKE))


def flesh_consistency():
    """
    What the flesh does when it is broken, drawn as the break itself. Snapping a stem
    is two seconds of work and separates whole families, so the drawings show the
    gesture and its result rather than a whole mushroom.
    """
    c = "flesh_consistency"

    write(f"art_{c}_soft", "Agaricus campestris",
          "Gives under a finger and keeps the dent.",
          path("M18,34 Q34,26 48,32 Q46,44 48,52 Q34,62 18,58 Z"),
          path("M78,34 Q62,26 48,32 Q50,44 48,52 Q62,62 78,58 Z"),
          # The finger that made the dent, coming down onto it.
          path("M48,8 L48,22 M42,16 L48,22 L54,16", width=FINE))
    write(f"art_{c}_brittle", "Russula virescens", "Snaps clean across, like chalk.",
          path("M14,34 L44,34 L48,50 L44,66 L14,66 Z"),
          path("M82,34 L56,34 L52,50 L56,66 L82,66 Z"),
          path("M46,26 L50,20 M52,26 L58,20", width=HAIR))
    write(f"art_{c}_fibrous", "Pleurotus ostreatus", "Tears into strands lengthways.",
          path("M14,32 L40,32 Q46,40 40,48 Q46,56 40,68 L14,68 Z"),
          path("M82,32 L56,32 Q50,40 56,48 Q50,56 56,68 L82,68 Z"),
          path("M40,36 L56,36 M40,46 L56,46 M40,58 L56,58", width=HAIR))
    write(f"art_{c}_leathery", "Trametes versicolor", "Bends without breaking.",
          path("M16,60 Q34,26 52,32 Q72,38 80,28"),
          path("M16,72 Q34,38 52,44 Q72,50 80,40"),
          path("M16,60 L16,72 M80,28 L80,40", width=FINE))
    write(f"art_{c}_woody", "Ganoderma applanatum", "Hard: it will not bend at all.",
          path("M18,34 L78,34 L78,64 L18,64 Z"),
          path("M26,34 L26,64 M38,34 L38,64 M50,34 L50,64 M62,34 L62,64 M70,34 L70,64",
               width=HAIR),
          path("M30,24 L36,18 M46,24 L46,16 M62,24 L58,18", width=HAIR))
    write(f"art_{c}_gelatinous", "Tremella mesenterica", "Rubbery and wobbling.",
          path("M22,54 Q20,36 34,34 Q44,24 56,34 Q74,34 74,52 Q76,72 48,74 "
               "Q22,72 22,54 Z"),
          path("M34,52 Q42,44 48,52 Q54,60 62,52", width=FINE),
          path("M14,44 L8,40 M14,58 L8,60 M82,44 L88,40 M82,58 L88,60", width=HAIR))
    write(f"art_{c}_powdery", "Lycoperdon perlatum", "Collapses to dust when mature.",
          path("M26,40 Q26,26 48,26 Q70,26 70,40 Q70,56 48,58 Q26,56 26,40 Z"),
          path("M30,68 L31,68 M40,72 L41,72 M50,70 L51,70 M60,74 L61,74 "
               "M36,80 L37,80 M48,82 L49,82 M62,80 L63,80 M22,76 L23,76 M70,68 L71,68",
               width=4))


def bruising_where():
    """Where the colour moved, shown by filling that part of a whole mushroom solid."""
    c = "bruising_where"

    def outline():
        return (
            path("M14,44 Q48,20 82,44 Q80,49 74,49 L22,49 Q14,49 14,44 Z"),
            path("M42,49 L42,84 M54,49 L54,84"),
            ground(),
        )

    write(f"art_{c}_cap", "—", "On the cap surface.",
          path("M14,44 Q48,20 82,44 Q80,49 74,49 L22,49 Q14,49 14,44 Z", fill=True),
          path("M42,49 L42,84 M54,49 L54,84"), ground())
    write(f"art_{c}_hymenophore", "—", "On the gills, pores or teeth.",
          *outline(),
          path("M20,49 L20,60 M27,49 L27,62 M34,49 L34,63 M62,49 L62,63 "
               "M69,49 L69,62 M76,49 L76,60", width=6))
    write(f"art_{c}_stipe", "—", "On the stem.",
          path("M14,44 Q48,20 82,44 Q80,49 74,49 L22,49 Q14,49 14,44 Z"),
          path("M42,49 L42,84 L54,84 L54,49 Z", fill=True), ground())
    write(f"art_{c}_flesh", "—", "Inside, on the face of a cut.",
          # Cut down the middle and opened: the whole exposed face is what changed.
          path("M12,44 Q30,22 46,40 L46,84 L34,84 L34,49 L20,49 Q12,49 12,44 Z"),
          path("M52,40 Q68,22 84,44 Q84,49 76,49 L62,49 L62,84 L50,84 L50,40 Z",
               fill=True),
          ground())
    write(f"art_{c}_stipe_base", "—", "At the base of the stem, and nowhere else.",
          *outline(),
          path("M42,70 L54,70 L54,84 L42,84 Z", fill=True))


def latex_change():
    c = "latex_change"

    def frame():
        return (
            path("M20,24 L20,44 L76,44 L76,24"),
            path("M20,56 L20,80 M76,56 L76,80"),
            path("M20,56 L76,56", width=FINE),
        )

    write(f"art_{c}_no", "Lactarius indigo",
          "The drop is the same colour minutes later.",
          *frame(),
          path("M36,46 Q32,52 36,55 Q41,55 41,50 Q41,48 39,44 Z", fill=True),
          path("M56,46 Q52,52 56,55 Q61,55 61,50 Q61,48 59,44 Z", fill=True),
          path("M46,64 L50,64 M46,70 L50,70", width=HAIR))
    write(f"art_{c}_yes", "Lactifluus volemus",
          "The drop changes as you watch, or stains what it touches.",
          *frame(),
          path("M36,46 Q32,52 36,55 Q41,55 41,50 Q41,48 39,44 Z", width=FINE),
          path("M56,46 Q52,52 56,55 Q61,55 61,50 Q61,48 59,44 Z", fill=True),
          path("M44,50 L52,50 M50,47 L53,50 L50,53", width=HAIR))


def substrate_wood():
    """
    What kind of wood, which is not a footnote: conifer against broadleaf is what
    separates angel wings from an oyster mushroom, and that pair has killed people.
    Drawn as the wood itself, with the tree that made it where it helps.
    """
    c = "substrate_wood"

    def log():
        return path("M12,40 Q12,32 20,32 L76,32 Q84,32 84,40 L84,60 Q84,68 76,68 "
                    "L20,68 Q12,68 12,60 Z")

    write(f"art_{c}_conifer", "—", "Pine, hemlock, spruce.",
          log(),
          path("M20,32 Q28,32 28,50 Q28,68 20,68", width=FINE),
          # A whole fir in silhouette, so this cannot be mistaken for the broadleaf
          # one. Angel wings against an oyster mushroom turns on this question.
          path("M48,4 L38,16 L44,16 L34,26 L62,26 L52,16 L58,16 Z", fill=True),
          path("M48,26 L48,32", width=FINE),
          path("M40,44 L40,56 M52,42 L52,58 M64,46 L64,54", width=HAIR))

    write(f"art_{c}_broadleaf", "—", "Oak, beech, poplar, maple.",
          log(),
          path("M20,32 Q28,32 28,50 Q28,68 20,68", width=FINE),
          path("M46,26 Q34,24 33,14 Q45,12 46,20 Q47,12 59,14 Q58,24 46,26 Z",
               width=FINE),
          path("M46,26 L46,30", width=HAIR),
          path("M40,44 Q46,48 40,54 M56,44 Q62,50 56,56", width=HAIR))

    write(f"art_{c}_living", "—", "A living tree, still standing.",
          path("M38,86 L38,34 Q38,24 48,24 Q58,24 58,34 L58,86"),
          path("M40,30 Q24,26 18,14 M56,30 Q72,26 78,14", width=FINE),
          path("M22,20 Q28,10 38,12 M74,20 Q68,10 58,12", width=HAIR),
          path("M44,46 Q48,52 44,58 M52,50 Q56,56 52,62", width=HAIR),
          ground(28, 68))

    write(f"art_{c}_dead", "—", "A dead stump, log or fallen branch.",
          path("M14,66 L26,34 Q28,28 34,30 L64,38 Q70,40 68,46 L60,70 Z"),
          path("M30,34 L58,42", width=HAIR),
          path("M34,46 L52,52 M30,56 L48,62", width=HAIR),
          path("M8,74 L88,74", width=FINE))

    write(f"art_{c}_bark", "—", "On the bark, not on wood the bark has left.",
          log(),
          path("M18,36 Q22,50 18,64 M26,34 Q30,50 26,66 M34,33 Q38,50 34,67 "
               "M42,32 Q46,50 42,68 M50,32 Q54,50 50,68 M58,32 Q62,50 58,68 "
               "M66,32 Q70,50 66,68 M74,33 Q78,50 74,67", width=HAIR))

    write(f"art_{c}_bare_wood", "—", "Bark gone; the wood itself is exposed.",
          log(),
          path("M20,32 Q26,50 20,68", width=FINE),
          path("M30,40 Q48,36 70,42 M30,50 Q48,46 70,52 M32,60 Q48,56 68,62",
               width=HAIR))

    write(f"art_{c}_woodchip", "—", "Mulch, chips or a bark bed.",
          path("M8,72 L88,72", width=FINE),
          path("M14,72 L22,60 L34,64 L28,72 Z"),
          path("M32,72 L38,58 L52,62 L48,72 Z"),
          path("M52,72 L60,60 L72,66 L68,72 Z"),
          path("M22,60 L28,54 M60,60 L66,54", width=HAIR))

    write(f"art_{c}_buried", "—", "Wood under the surface, found only by digging.",
          path("M10,44 L86,44"),
          path("M22,74 Q22,66 30,66 L62,66 Q70,66 70,74 Q70,82 62,82 L30,82 "
               "Q22,82 22,74 Z"),
          path("M30,66 Q36,74 30,82", width=HAIR),
          path("M18,54 L28,54 M38,52 L50,52 M58,54 L70,54 M26,60 L36,60 M52,60 L64,60",
               width=HAIR))


def bruising_speed():
    """A clock face, filled by how much of it passes before the colour moves."""
    c = "bruising_speed"

    def dial():
        return path("M48,16 Q80,16 80,48 Q80,80 48,80 Q16,80 16,48 Q16,16 48,16 Z")

    write(f"art_{c}_instant", "Suillellus subvelutipes",
          "The colour is already moving as the knife leaves.",
          dial(),
          path("M48,26 L48,48 L58,54", width=FINE),
          path("M48,48 L48,26 A22,22 0 0,1 62,32 Z", fill=True))

    write(f"art_{c}_minute", "—", "Within a minute or so.",
          dial(),
          path("M48,26 L48,48 L64,48", width=FINE),
          path("M48,48 L48,26 A22,22 0 0,1 70,48 Z", fill=True))

    write(f"art_{c}_slow", "—", "Several minutes, and easy to miss.",
          dial(),
          path("M48,26 L48,48 L48,70", width=FINE),
          path("M48,48 L48,26 A22,22 0 1,1 48,70 Z", fill=True))


def launcher():
    write("art_launcher_chanterelle",
          "Cantharellus lateritius",
          "The launcher mark: wavy funnel cap and blunt decurrent ridges.",
          path("M12,36 Q24,22 36,32 Q48,20 60,31 Q74,22 84,36 "
               "L64,60 Q56,72 54,88 L42,88 Q40,72 32,60 Z"),
          path("M24,42 Q31,62 38,84 M38,39 Q42,60 44,86 M54,39 Q52,60 52,86 "
               "M68,42 Q60,60 55,82", width=FINE),
          path("M28,52 Q31,57 34,52 M46,49 Q49,54 52,49 M58,54 Q61,58 64,54",
               width=HAIR))


def interface_icons():
    """
    The two marks the interface itself needs. Written here so they share the hand.

    Not prefixed art_, because they are not character states and must not appear in
    the generated map or the contact sheet.
    """
    def plain(name, *paths):
        with open(os.path.join(OUT, f"{name}.xml"), "w") as f:
            f.write(HEADER + "".join(paths) + FOOTER)

    # An outlined i, per the house rule that About is an i in the corner.
    plain("ic_about",
          path("M48,12 Q84,12 84,48 Q84,84 48,84 Q12,84 12,48 Q12,12 48,12 Z"),
          path("M48,30 L48,32", width=7),
          path("M48,42 L48,66", width=6))

    plain("ic_remove",
          path("M24,32 L72,32"),
          path("M38,32 L38,24 Q38,20 42,20 L54,20 Q58,20 58,24 L58,32"),
          path("M30,32 L34,76 Q34,80 38,80 L58,80 Q62,80 62,76 L66,32"),
          path("M42,42 L43,70 M54,42 L53,70", width=FINE))


def launcher_icon():
    """
    The launcher mark: a chanterelle, drawn from a chosen reference.

    Three earlier attempts failed and all three failed the same way — a symmetric,
    front-on silhouette that read as wings, a tulip or a pair of quote marks. The
    reference he pointed at (a hand-drawn fly agaric, pictureboxblue) shows why: it is a
    **three-quarter view**, tilted so the eye sees the top of the cap *and* into the
    underside at once, with the gills as fine radiating hatching. That is what makes it
    read as a mushroom in one look rather than as a shape.

    So this is the same view for a chanterelle: looking slightly down into the funnel,
    wavy rim, the blunt decurrent ridges running down the front, and one confident
    outline. Outline only, per the reference — no solid fill.
    """
    W = 6.0
    inner = "".join([
        # The reference's geometry, not my idea of a chanterelle. Four attempts drew a
        # symmetric V — a vase seen dead on — and every one read as wings or a crown.
        # The fly agaric in the reference reads instantly because it is a cap *mass*
        # seen from above and in front, with a stem beneath it. So: the same, with a
        # chanterelle's wavy rim and its funnel showing.
        path("M13,41 Q15,25 33,22 Q48,15 63,22 Q82,26 84,42 "
             "Q68,55 48,56 Q26,55 13,41 Z", width=W),
        # The funnel, seen into.
        path("M30,33 Q48,44 66,32", width=W - 2.0),
        # The stem below, one shape, narrowing.
        path("M40,55 Q39,72 42,88 L54,88 Q57,72 56,55", width=W),
        # Ridges running off the near rim onto the stem.
        path("M31,53 Q30,62 31,70 M64,52 Q66,62 65,70", width=W - 2.5),
    ])
    body = (
        '    <group android:scaleX="0.75" android:scaleY="0.75"\n'
        '        android:translateX="18" android:translateY="18">\n'
        + inner +
        '    </group>\n'
    )
    head = HEADER.replace('android:width="96dp"', 'android:width="108dp"') \
                 .replace('android:height="96dp"', 'android:height="108dp"') \
                 .replace('android:viewportWidth="96"', 'android:viewportWidth="108"') \
                 .replace('android:viewportHeight="96"', 'android:viewportHeight="108"')
    with open(os.path.join(OUT, "ic_launcher_foreground.xml"), "w") as f:
        f.write(head + body + FOOTER)
    print("  launcher foreground: chanterelle, three-quarter, from the owner's reference")


def emit_kotlin():
    """
    The map the app draws from, plus what each drawing is of.

    Generated rather than hand-kept so a new drawing cannot be added without its
    provenance, and so the two can never drift apart.
    """
    rows = []
    for name in sorted(EXEMPLARS):
        if name.startswith("art_launcher"):
            continue
        body = name[len("art_"):]
        species, why = EXEMPLARS[name]
        # Longest character id wins, so gill_edge does not swallow gill_edge_even.
        rows.append((body, name, species, why))

    def split(body):
        for cid in sorted(CHARACTERS, key=len, reverse=True):
            if body.startswith(cid + "_"):
                return cid, body[len(cid) + 1:]
        raise SystemExit(f"cannot split {body}")

    lines = [
        "package com.wanderwildwood.kinokocho.ui",
        "",
        "import com.wanderwildwood.kinokocho.R",
        "",
        "/**",
        " * The drawing for a character state, and the mushroom it was drawn from.",
        " *",
        " * Generated by tools/make-art.py. Do not edit by hand.",
        " *",
        " * Naming the species is not the app identifying anything — it is saying what the",
        " * picture is of, the way a field guide captions a plate. A reader who wants to know",
        " * why decurrent looks like that gets an answer; the mushroom in their hand is never",
        " * named by this app.",
        " */",
        "data class Art(val drawable: Int, val species: String?, val note: String)",
        "",
        "object CharacterArt {",
        "",
        "    private val byState: Map<String, Art> = mapOf(",
    ]
    for body, name, species, why in rows:
        cid, vid = split(body)
        sp = "null" if species == "—" else f"\"{species}\""
        lines.append(f'        "{cid}/{vid}" to Art(R.drawable.{name}, {sp}, "{why}"),')
    lines += [
        "    )",
        "",
        "    /** The drawing for a state, or null where none has been drawn yet. */",
        "    fun of(characterId: String, valueId: String): Art? = byState[\"$characterId/$valueId\"]",
        "",
        "    /** True when every state of a character has a drawing, so a grid is safe. */",
        "    fun coversAll(characterId: String, valueIds: List<String>): Boolean =",
        "        valueIds.isNotEmpty() && valueIds.all { byState.containsKey(\"$characterId/$it\") }",
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(KT), exist_ok=True)
    with open(KT, "w") as f:
        f.write("\n".join(lines))


CHARACTERS = [
    "fruitbody_type", "gill_attachment", "stipe_base", "cap_shape", "ring",
    "stipe_presence", "gill_spacing", "growth_habit", "cap_margin", "veil_remnants",
    "gill_edge", "stipe_flesh", "gill_extras", "cap_colour_pattern",
    "substrate", "latex", "bruising", "associated_tree",
    "cap_surface", "stipe_surface", "flesh_consistency", "bruising_where",
    "latex_change", "substrate_wood", "bruising_speed",
]

if __name__ == "__main__":
    fruitbody_type()
    gill_attachment()
    stipe_base()
    cap_shape()
    ring()
    stipe_presence()
    gill_spacing()
    growth_habit()
    cap_margin()
    veil_remnants()
    gill_edge()
    stipe_flesh()
    gill_extras()
    cap_colour_pattern()
    substrate()
    latex()
    bruising()
    associated_tree()
    cap_surface()
    stipe_surface()
    flesh_consistency()
    bruising_where()
    latex_change()
    substrate_wood()
    bruising_speed()
    launcher()
    interface_icons()
    launcher_icon()
    emit_kotlin()
    n = len([f for f in os.listdir(OUT) if f.startswith("art_")])
    species = sorted({s for s, _ in EXEMPLARS.values() if s != "—"})
    print(f"{n} drawings, from {len(species)} species")
    for s in species:
        print(f"  {s}")
